# BNP Paribas- Bussines Case Project 2025/2026
**DATA VISUALIZATION AND PREPROCESSING NOTEBOOK**

**Group V**:
   - Alano Gonçalves (20250457)
   - Catarina Martins (20221914)
   - João Carichas (20250507)
   - Marta Ribeiro (20221886)
   - Nicole Nogueira(20221961)

# Index

- [1. Import](#import)
  - [1.1 Import libraries](#import-libraries)
  - [1.2 Import the dataset](#import-the-dataset)
- [2. Data Exploration](#data-Exploration)
  - [2.1 MetaData](#metadata)
  - [2.2 Analysing the Data](#Analysing-the-Data)
  - [2.3 Data Visualization](#Data-visualization)
  - [2.4 Correlation Check](#correlation-check)
- [3. Data Quality & Feature Engineering](#Data-Quality-&-Feature-Engineering)
  - [3.1 Data Quality](#Data-Quality)
  - [3.2 Feature Engineering](#Feature-Engineering)
- [4. Implications for Clustering](#Implications-for-Clustering)

<div class="alert alert-block alert-info">

<a class="anchor" id="1. Import">    </a>
# 1. Import
       
</div>

[Back to Index](#index)

<a class="anchor" id="1.1 Import Libraries">

## 1.1 Import Libraries
    
</a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from math import ceil
from suport import *
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score   
from sklearn.impute import KNNImputer

<a class="anchor" id="1.2 Import the Dataset">

## 1.2 Import the Dataset
    
</a>

In [ ]:
#pip install pandas pyarrow
#!pip install fastparquet

In [ ]:
#Alano
file_path_CRC = r"C:\Users\alano\Desktop\Mestrado\2- Semestre\Busines case\BNP\Projeto GIt\crc.parquet"
file_path_CREDSCORE = r"C:\Users\alano\Desktop\Mestrado\2- Semestre\Busines case\BNP\Projeto GIt\BNP-Paribas\credscore.parquet"
file_path_BDOSS = r"C:\Users\alano\Desktop\Mestrado\2- Semestre\Busines case\BNP\Projeto GIt\bdoss.parquet"
file_path_FAMA = r"C:\Users\alano\Desktop\Mestrado\2- Semestre\Busines case\BNP\Projeto GIt\BNP-Paribas\fama.parquet"

# Ler o ficheiro parquet
CRC = pd.read_parquet(file_path_CRC, engine="fastparquet")
CREDSCORE = pd.read_parquet(file_path_CREDSCORE, engine="fastparquet")
FAMA = pd.read_parquet(file_path_FAMA, engine="fastparquet")
BDOSS = pd.read_parquet(file_path_BDOSS, engine="fastparquet")

In [ ]:
#joão
file_path_CRC = r"C:\Users\jcari\OneDrive\Ambiente de Trabalho\NOVA IMS\Business Cases\Case 1\crc.parquet"
file_path_CREDSCORE = r"C:\Users\jcari\OneDrive\Ambiente de Trabalho\BNP-Paribas-main\credscore.parquet"
file_path_BDOSS = r"C:\Users\jcari\OneDrive\Ambiente de Trabalho\NOVA IMS\Business Cases\Case 1\bdoss.parquet"
file_path_FAMA = r"C:\Users\jcari\OneDrive\Ambiente de Trabalho\BNP-Paribas-main\fama.parquet"

# Ler o ficheiro parquet
CRC = pd.read_parquet(file_path_CRC, engine="fastparquet")
CREDSCORE = pd.read_parquet(file_path_CREDSCORE, engine="fastparquet")
FAMA = pd.read_parquet(file_path_FAMA, engine="fastparquet")
BDOSS = pd.read_parquet(file_path_BDOSS, engine="fastparquet")

In [ ]:
#marta
file_path_CRC = r"C:\Users\martr\OneDrive\Documentos\GitHub\crc.parquet"
file_path_CREDSCORE = r"C:\Users\martr\OneDrive\Documentos\GitHub\BNP-Paribas\credscore.parquet"
file_path_BDOSS = r"C:\Users\martr\OneDrive\Documentos\GitHub\BDOSS.parquet"
file_path_FAMA = r"C:\Users\martr\OneDrive\Documentos\GitHub\BNP-Paribas\fama.parquet"

# Ler o ficheiro parquet
CRC = pd.read_parquet(file_path_CRC, engine="fastparquet")
CREDSCORE = pd.read_parquet(file_path_CREDSCORE, engine="fastparquet")
FAMA = pd.read_parquet(file_path_FAMA, engine="fastparquet")
BDOSS = pd.read_parquet(file_path_BDOSS, engine="fastparquet")

In [2]:
#nicole
file_path_CRC = r"C:\Users\nicol\OneDrive\Documents\MDSAA\Business Cases\Projeto BC\crc.parquet"
file_path_CREDSCORE = r"C:\Users\nicol\OneDrive\Documents\MDSAA\Business Cases\Projeto BC\Dataset\credscore.parquet"
file_path_BDOSS = r"C:\Users\nicol\OneDrive\Documents\MDSAA\Business Cases\Projeto BC\bdoss.parquet"
file_path_FAMA = r"C:\Users\nicol\OneDrive\Documents\MDSAA\Business Cases\Projeto BC\Dataset\fama.parquet"

# Ler o ficheiro parquet
CRC = pd.read_parquet(file_path_CRC, engine="fastparquet")
CREDSCORE = pd.read_parquet(file_path_CREDSCORE, engine="fastparquet")
FAMA = pd.read_parquet(file_path_FAMA, engine="fastparquet")
BDOSS = pd.read_parquet(file_path_BDOSS, engine="fastparquet")

<div class="alert alert-block alert-info">

<a class="anchor" id="2. Data Exploration">    </a>
# CRC Dataset
       
</div>

**METADATA:**
- *Date_Obs*: Observation Date (MMYY).
- *MT_MENSAL*: Sum of monthly installments paid by the client.
- *COUNT_CL*: Consumer credit count.
- *COUNT_CP*: Credit card or revolving credit count.
- *COUNT_AUTO*:  Auto loan credit count.
- *COUNT_HT*: Mortgage credit count.
- *COUNT_CONEXO*: Connected credit count.
- *COUNT_OTHER*: Other credits count.
- *COUNT_TOTAL*: Total credits count.
- *MONTVENC_CL*:  Sum of overdue amounts in consumer credit. 
- *MONTVENC_CP*:  Sum of overdue amounts in credit card and revolving credit.
- *MONTVENC_AUTO*:  Sum of overdue amounts in auto loans.
- *MONTVENC_HT*:  Sum of overdue amounts in mortgages.
- *MONTABATV_CL*:  Sum of written-off amounts in consumer credit.
- *MONTABATV_CP*:  Sum of written-off amounts in credit card and revolving credit.
- *MONTABATV_AUTO*:  Sum of written-off amounts in auto loans.
- *MONTABATV_HT*:  Sum of written-off amounts in mortgages.
- *DIVIDAS_CL*:   Total consumer credit debt.
- *DIVIDAS_CP*:  Total credit card and revolving credit debt.
- *DIVIDAS_AUTO*: Total auto loan debt.
- *DIVIDAS_HT*: Total mortgage debt.

<a class="anchor" id="2.2 Analysing the Data">

## 2. Analysing the Data
    
</a>

### 2.1. Data Overview

In [ ]:
CRC.info()

- The most important (serious ones) are the MONTABATV. If those variables are too high, the client is not trustworthy.
- It is normal for a client to have DIVIDAS, but is preferable if they reduce month to month.

In [ ]:
CRC.describe().round(2)

In [ ]:
CRC.tail()

In [ ]:
CRC = CRC.sort_values(['CONTRIB', 'OBS_DATE'])

In [ ]:
#To each client, check the maximum and minimum number of each variable
CRC.groupby('CONTRIB').agg(['min', 'max'])

In [ ]:
#how many months of data do we have per client
CRC['CONTRIB'].value_counts()

In [ ]:
pd.set_option('display.max_columns', None)
CRC.sort_values(by=['CONTRIB','OBS_DATE'], ascending=False)
CRC.head(26)

In [ ]:
CRC['DIVIDAS_CL'].value_counts(dropna=False)

### 2.2. Checking Duplicates

In [ ]:
#checking number of duplicates
CRC.duplicated().sum()

### 2.3. Checking Missing Values

In [ ]:
#checking number of missing values
CRC.isna().sum()

In [ ]:
#checking umber of missing values in each column as a percentage
CRC.isna().sum()/len(CRC) * 100

- MT_MENSAL have a lot of missing values (more than 66% of the observations are missing values)- it is likely to be a variable that do not gives us much information 
- All variables (except for *OBS_DATE*) have the same number of missing values which is likely to be the same observations- therefore it can be removed.

In [ ]:
CRC[CRC['COUNT_CL'].isna()]

In [ ]:
CRC[CRC['COUNT_CP'].isna()]

In [ ]:
CRC[CRC['CONTRIB'] == 'c7e93bc661a9d5329ea48d365935197aecff39161303b6bf625189371f7ac23c']

- There are clients that do not have information about the all 25 months

### 2.4. Checking Outliers

In [ ]:
metric_features= [ 'MT_MENSAL','COUNT_CL', 'COUNT_CP', 'COUNT_AUTO', 'COUNT_HT', 'COUNT_CONEXO', 'COUNT_OTHER', 'COUNT_TOTAL', 'MONTVENC_CL', 'MONTVENC_CP', 'MONTVENC_AUTO', 'MONTVENC_HT', 'MONTABATV_CL', 'MONTABATV_CP', 'MONTABATV_AUTO', 'MONTABATV_HT', 'DIVIDAS_CL', 'DIVIDAS_CP', 'DIVIDAS_AUTO', 'DIVIDAS_HT']

In [ ]:
def plot_multiple_boxplots(data, feats, n_cols=3, title="Numeric Variables' Box Plots (>0 only)"):
    
    n_rows = ceil(len(feats) / n_cols)
    
    fig, axes = plt.subplots(
        n_rows,
        n_cols,
        figsize=(6 * n_cols, 4.5 * n_rows)
    )
    
    axes = axes.flatten()
    
    for i, feat in enumerate(feats):
        
        # Keep only values strictly greater than 0
        values = data[feat]
        values = values[(values > 0) & (values.notna())]
        
        if len(values) > 0:
            sns.boxplot(x=values, ax=axes[i])
            axes[i].set_title(feat, fontsize=10)
        else:
            axes[i].set_title(f"{feat} (no >0 values)", fontsize=10)
    
    # Remove unused subplots
    for j in range(len(feats), len(axes)):
        fig.delaxes(axes[j])
    
    plt.suptitle(title, fontsize=18)
    plt.tight_layout(rect=[0, 0, 1, 0.97])
    plt.show()

In [ ]:
#applying the function to our numerical features
plot_multiple_boxplots(CRC, metric_features)

In [ ]:
CRC[CRC['COUNT_CL'] > 50].count()

In [ ]:
CRC[CRC['COUNT_CP'] > 100].count()

In [ ]:
CRC[CRC['COUNT_AUTO'] > 15].count()

In [ ]:
CRC[CRC['COUNT_HT'] > 20].count()

In [ ]:
CRC[CRC['COUNT_CONEXO'] > 10].count()

In [ ]:
CRC[CRC['COUNT_OTHER'] > 30].count()

In [ ]:
CRC[CRC['MONTVENC_CL'] > 300000].count()

In [ ]:
CRC[CRC['MONTVENC_CP'] > 60000].count()

In [ ]:
CRC[CRC['MONTVENC_AUTO'] > 70000].count()

In [ ]:
CRC[CRC['MONTVENC_HT'] > 400000].count()

In [ ]:
CRC[CRC['MONTABATV_CL'] > 50000].count()

In [ ]:
CRC[CRC['MONTABATV_CP'] > 30000].count()

In [ ]:
CRC[CRC['MONTABATV_AUTO'] > 10000].count()

In [ ]:
CRC[CRC['MONTABATV_HT'] > 100000].count()

In [ ]:
CRC[CRC['DIVIDAS_CL'] > 1000000].count()

In [ ]:
CRC[CRC['DIVIDAS_CP'] > 200000].count()

In [ ]:
CRC[CRC['DIVIDAS_AUTO'] > 300000].count()

In [ ]:
CRC[CRC['DIVIDAS_HT'] > 2000000].count()

In [ ]:
def plot_multiple_boxplots(data, feats, n_cols=3, title="Numeric Variables' Box Plots"):
    
    n_rows = ceil(len(feats) / n_cols)
    
    fig, axes = plt.subplots(
        n_rows,
        n_cols,
        figsize=(6 * n_cols, 4.5 * n_rows)
    )
    
    axes = axes.flatten()  # flatten in case of multiple rows
    
    for i, feat in enumerate(feats):
        sns.boxplot(
            x=data[feat],
            ax=axes[i]
        )
        axes[i].set_title(feat, fontsize=10)
    
    # Remove empty subplots
    for j in range(len(feats), len(axes)):
        fig.delaxes(axes[j])
    
    plt.suptitle(title, fontsize=18)
    plt.tight_layout(rect=[0, 0, 1, 0.97])
    plt.show()

### 2.5. Checking Distribution

In [ ]:
df= pd.DataFrame(CRC[metric_features])

In [ ]:
# Sampling
N = 200_000
sample = CRC.sample(n=min(N, len(CRC)), random_state=42)

cols = sample.select_dtypes(include=[np.number]).columns  # all 20 variables

plots_per_fig = 6   # 2 rows x 3 cols
n_figs = ceil(len(cols) / plots_per_fig)

for f in range(n_figs):
    
    start = f * plots_per_fig
    end = start + plots_per_fig
    subset_cols = cols[start:end]
    
    fig, axes = plt.subplots(2, 3, figsize=(14, 8))
    axes = axes.ravel()
    
    for ax, col in zip(axes, subset_cols):
        sns.histplot(sample[col].dropna(), bins=60, kde=False, ax=ax)
        ax.set_title(col, fontsize=10)
    
    # Remove empty subplots if last figure has fewer than 6 plots
    for j in range(len(subset_cols), len(axes)):
        fig.delaxes(axes[j])
    
    plt.tight_layout()
    plt.show()

### 2.6. Checking Correlation between variables

In [ ]:
#checking correlation between variables 
#we are going to use spearman correlation since our variables do not follow a normal distribution
cor_spearman = CRC[metric_features].corr(method ='spearman')
cor_spearman

In [ ]:
#creating correlation matrix to facilitate interpretation
def cor_heatmap(cor):
    
    #setting the figure size
    plt.figure(figsize=(12, 10))

    #creating a mask for the upper triangle of the matrix (to avoid plotting duplicate correlation values)
    mask = np.triu(np.ones_like(cor, dtype=bool))

    #plotting the correlation heatmap
    sns.heatmap(
        data=cor,                 #correlation matrix input
        mask=mask,                #applying upper-triangle mask
        annot=True,               #displaying correlation coefficients
        cmap='YlGnBu',            #color map for visual contrast
        fmt='.2f',                #formatting values to two decimals
        square=True,              #ensuring square-shaped cells
        linewidths=0.5,           #adding grid lines between cells
        cbar_kws={"shrink": 0.8}  #adjusting color bar size
    )

    #adding a title and display the plot
    plt.title("Spearman Correlation Matrix", fontsize=14)
    plt.show()

'''This function visualises a correlation matrix using a heatmap to
facilitate interpretation of relationships between variables. By 
masking the upper triangle of the matrix, the plot avoids redundant
information and improves the readability. '''

In [ ]:
#applying the function to our numerical features
cor_heatmap(cor_spearman)

In [ ]:
sns.set()

sample_df = df[metric_features].sample(1000, random_state=42)

sns.pairplot(
    sample_df,
    diag_kind="hist"
)

plt.subplots_adjust(top=0.95)
plt.suptitle(
    "Pairwise Relationship of Numerical Variables",
    fontsize=20
)

plt.show()

### 2.7. Checking Incoherencies

In [ ]:
CRC[CRC['COUNT_CL'] > CRC['DIVIDAS_CL']]

In [ ]:
CRC[CRC['COUNT_CP'] > CRC['DIVIDAS_CP']]

In [ ]:
CRC[
    CRC['COUNT_CL'] +
    CRC['COUNT_CP'] +
    CRC['COUNT_AUTO'] +
    CRC['COUNT_HT'] +
    CRC['COUNT_CONEXO'] +
    CRC['COUNT_OTHER']
    != CRC['COUNT_TOTAL']
]

<a class="anchor" id="2.2 Analysing the Data">

## 3. Data Preparation
    
</a>

### 3.1. Changing Datatypes

In [ ]:
#CRC.set_index('CONTRIB', inplace = True)

In [3]:
#Changing Datatypes
CRC['COUNT_CL'] = CRC['COUNT_CL'].round().astype('Int32')
CRC['COUNT_CP'] = CRC['COUNT_CP'].round().astype('Int32')
CRC['COUNT_AUTO'] = CRC['COUNT_AUTO'].round().astype('Int32')
CRC['COUNT_HT'] = CRC['COUNT_HT'].round().astype('Int32')
CRC['COUNT_CONEXO'] = CRC['COUNT_CONEXO'].round().astype('Int32')
CRC['COUNT_OTHER'] = CRC['COUNT_OTHER'].round().astype('Int32')
CRC['COUNT_TOTAL'] = CRC['COUNT_TOTAL'].round().astype('Int32')

### 3.2. Handling Missing Values

In [4]:
#handling missing values of 172 rows
CRC = CRC.dropna(subset=['COUNT_CL'])

In [5]:
#droping MT_MENSAL due to its elevated number of missing values
CRC = CRC.drop(columns=['MT_MENSAL'])

In [6]:
#checking number of missing values
CRC.isna().sum()

CONTRIB           0
OBS_DATE          0
COUNT_CL          0
COUNT_CP          0
COUNT_AUTO        0
COUNT_HT          0
COUNT_CONEXO      0
COUNT_OTHER       0
COUNT_TOTAL       0
MONTVENC_CL       0
MONTVENC_CP       0
MONTVENC_AUTO     0
MONTVENC_HT       0
MONTABATV_CL      0
MONTABATV_CP      0
MONTABATV_AUTO    0
MONTABATV_HT      0
DIVIDAS_CL        0
DIVIDAS_CP        0
DIVIDAS_AUTO      0
DIVIDAS_HT        0
dtype: int64

### 3.3. Handling Outliers

In [7]:
CRC['COUNT_CL'] = CRC['COUNT_CL'].clip(upper=50)
CRC['COUNT_CP'] = CRC['COUNT_CP'].clip(upper=100)
CRC['COUNT_AUTO'] = CRC['COUNT_AUTO'].clip(upper=15)
CRC['COUNT_HT'] = CRC['COUNT_HT'].clip(upper=20)
CRC['COUNT_CONEXO'] = CRC['COUNT_CONEXO'].clip(upper=10)
CRC['COUNT_OTHER'] = CRC['COUNT_OTHER'].clip(upper=30)
CRC['MONTVENC_CL'] = CRC['MONTVENC_CL'].clip(upper=300000)
CRC['MONTVENC_CP'] = CRC['MONTVENC_CP'].clip(upper=60000)
CRC['MONTVENC_AUTO'] = CRC['MONTVENC_AUTO'].clip(upper=70000)
CRC['MONTVENC_HT'] = CRC['MONTVENC_HT'].clip(upper=400000)
CRC['MONTABATV_CL'] = CRC['MONTABATV_CL'].clip(upper=50000)
CRC['MONTABATV_CP'] = CRC['MONTABATV_CP'].clip(upper=30000)
CRC['MONTABATV_AUTO'] = CRC['MONTABATV_AUTO'].clip(upper=10000)
CRC['MONTABATV_HT'] = CRC['MONTABATV_HT'].clip(upper=100000)
CRC['DIVIDAS_CL'] = CRC['DIVIDAS_CL'].clip(upper=1000000)
CRC['DIVIDAS_CP'] = CRC['DIVIDAS_CP'].clip(upper=200000)
CRC['DIVIDAS_AUTO'] = CRC['DIVIDAS_AUTO'].clip(upper=300000)
CRC['DIVIDAS_HT'] = CRC['DIVIDAS_HT'].clip(upper=300000)

In [8]:
#checking if 'COUNT_TOTAL' is well calculated after handling outliers
CRC[
    CRC['COUNT_CL'] +
    CRC['COUNT_CP'] +
    CRC['COUNT_AUTO'] +
    CRC['COUNT_HT'] +
    CRC['COUNT_CONEXO'] +
    CRC['COUNT_OTHER']
    != CRC['COUNT_TOTAL']
]

,CONTRIB,OBS_DATE,COUNT_CL,COUNT_CP,COUNT_AUTO,COUNT_HT,COUNT_CONEXO,COUNT_OTHER,COUNT_TOTAL,MONTVENC_CL,...,MONTVENC_AUTO,MONTVENC_HT,MONTABATV_CL,MONTABATV_CP,MONTABATV_AUTO,MONTABATV_HT,DIVIDAS_CL,DIVIDAS_CP,DIVIDAS_AUTO,DIVIDAS_HT
7732,10d819a5d3374566b01cc287e212bfd30ccabb911bacf7...,2023-12-31,0,15,3,20,0,9,57,0.00,...,0.00,0.0,0.0,0.0,0.0,0.0,0.00,16445.31,53071.71,300000.00
89652,c1084cf8628c8ad5352c03c4a8d903621dcaca9b4b7b61...,2023-12-31,8,16,15,0,0,0,40,0.00,...,0.00,0.0,0.0,0.0,0.0,0.0,83601.36,119.92,68089.52,0.00
152211,47639645b5408e171d103a50a4eae026ba4b4c8b8c822f...,2024-01-31,16,48,15,8,0,0,88,0.00,...,0.00,0.0,0.0,0.0,0.0,0.0,290330.80,24698.32,135622.16,300000.00
185404,8ee439f9fe287cda494b1cc50c8d7b955df2552b2eeb65...,2024-01-31,24,24,15,8,8,24,104,0.00,...,0.00,0.0,0.0,0.0,0.0,0.0,165744.48,2816.40,177547.52,124740.24
193078,9f3454d721886d7629fe2c0ad169579d79e7cd10e54675...,2024-01-31,0,24,15,8,0,8,56,0.00,...,0.00,0.0,0.0,0.0,0.0,0.0,0.00,1455.92,96033.76,300000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2820550,3c9a565cadf56ff1554623a9273255fc546d96b2687dd7...,2025-11-30,16,0,15,0,0,4,36,323.88,...,4838.36,0.0,0.0,0.0,0.0,0.0,166320.04,0.00,175980.52,0.00
2859534,8ee439f9fe287cda494b1cc50c8d7b955df2552b2eeb65...,2025-11-30,24,16,15,8,8,24,96,0.00,...,0.00,0.0,0.0,0.0,0.0,0.0,114909.60,2672.96,194108.00,106210.88
2946646,45e07fa5cc2621083b672ed204306b9a99e52e41698a6e...,2025-12-31,50,100,10,10,0,20,200,0.00,...,0.00,0.0,0.0,0.0,0.0,0.0,925475.50,200000.00,47171.10,300000.00
3011933,cfa7e105c17b77302c2753081d0517ac9a602dfd4edbb5...,2025-12-31,2,10,15,0,0,2,30,352.10,...,18573.56,0.0,0.0,0.0,0.0,0.0,9885.00,31044.22,300000.00,0.00
3016859,da3a6b0258652edaf2d9f6037c2723082bc955cf403d03...,2025-12-31,50,18,0,0,0,18,90,273069.45,...,0.00,0.0,50000.0,0.0,0.0,0.0,603017.55,50917.32,0.00,0.00

In [9]:
components = [
    'COUNT_CL',
    'COUNT_CP',
    'COUNT_AUTO',
    'COUNT_HT',
    'COUNT_CONEXO',
    'COUNT_OTHER'
]

# Calculate the correct sum
component_sum = CRC[components].sum(axis=1)

# Replace COUNT_TOTAL only where it is different
CRC.loc[CRC['COUNT_TOTAL'] != component_sum, 'COUNT_TOTAL'] = component_sum

### 3.4. Feature Engineering

In [10]:
CRC.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3034749 entries, 0 to 3034920
Data columns (total 21 columns):
 #   Column          Dtype
---  ------          -----
 0   CONTRIB         object
 1   OBS_DATE        datetime64[ns]
 2   COUNT_CL        Int32
 3   COUNT_CP        Int32
 4   COUNT_AUTO      Int32
 5   COUNT_HT        Int32
 6   COUNT_CONEXO    Int32
 7   COUNT_OTHER     Int32
 8   COUNT_TOTAL     Int32
 9   MONTVENC_CL     float64
 10  MONTVENC_CP     float64
 11  MONTVENC_AUTO   float64
 12  MONTVENC_HT     float64
 13  MONTABATV_CL    float64
 14  MONTABATV_CP    float64
 15  MONTABATV_AUTO  float64
 16  MONTABATV_HT    float64
 17  DIVIDAS_CL      float64
 18  DIVIDAS_CP      float64
 19  DIVIDAS_AUTO    float64
 20  DIVIDAS_HT      float64
dtypes: Int32(7), datetime64[ns](1), float64(12), object(1)
memory usage: 513.1+ MB

In [11]:
#creating 'SUBCOUNT_TOTAL'
CRC['SUBCOUNT_TOTAL'] = CRC[
    ['COUNT_CL','COUNT_CP','COUNT_AUTO','COUNT_HT']
].sum(axis=1)

In [12]:
#creating 'MONTVENC_TOTAL'
CRC['MONTVENC_TOTAL'] = CRC[
    ['MONTVENC_CL','MONTVENC_CP','MONTVENC_AUTO','MONTVENC_HT']
].sum(axis=1)

In [13]:
#creating 'MONTABATV_TOTAL'
CRC['MONTABATV_TOTAL'] = CRC[
    ['MONTABATV_CL','MONTABATV_CP','MONTABATV_AUTO','MONTABATV_HT']
].sum(axis=1)

In [14]:
#creating 'DIVIDAS_TOTAL'
CRC['DIVIDAS_TOTAL'] = CRC[
    ['DIVIDAS_CL','DIVIDAS_CP','DIVIDAS_AUTO','DIVIDAS_HT']
].sum(axis=1)

In [ ]:
'''CRC['BALANCE_CL'] = (CRC['MONTVENC_CL'] - CRC['MONTABATV_CL'])
CRC['BALANCE_CP'] = (CRC['MONTVENC_CP'] - CRC['MONTABATV_CP'])
CRC['BALANCE_AUTO'] = (CRC['MONTVENC_AUTO'] - CRC['MONTABATV_AUTO'])
CRC['BALANCE_HT'] = (CRC['MONTVENC_HT'] - CRC['MONTABATV_HT'])

cols_to_move = ['BALANCE_CL', 'BALANCE_CP', 'BALANCE_AUTO', 'BALANCE_HT']

for col in reversed(cols_to_move):
    col_data = CRC.pop(col)
    CRC.insert(10, col, col_data)'''

In [ ]:
#CRC = CRC.drop(columns=['MONTVENC_CL', 'MONTABATV_CL', 'MONTVENC_CP', 'MONTABATV_CP', 'MONTVENC_AUTO', 'MONTABATV_AUTO', 'MONTVENC_HT', 'MONTABATV_HT', 'MONTVENC_TOTAL', 'MONTABATV_TOTAL'])

In [15]:
pd.set_option('display.max_columns', None)
CRC = CRC.sort_values(['CONTRIB', 'OBS_DATE'])
CRC.tail(30)

,CONTRIB,OBS_DATE,COUNT_CL,COUNT_CP,COUNT_AUTO,COUNT_HT,COUNT_CONEXO,COUNT_OTHER,COUNT_TOTAL,MONTVENC_CL,MONTVENC_CP,MONTVENC_AUTO,MONTVENC_HT,MONTABATV_CL,MONTABATV_CP,MONTABATV_AUTO,MONTABATV_HT,DIVIDAS_CL,DIVIDAS_CP,DIVIDAS_AUTO,DIVIDAS_HT,SUBCOUNT_TOTAL,MONTVENC_TOTAL,MONTABATV_TOTAL,DIVIDAS_TOTAL
717013,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2024-05-31,2,1,0,0,0,0,3,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,17345.04,3320.12,0.00,0.0,3,0.00,0.0,20665.16
837416,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2024-06-30,2,1,0,0,0,0,3,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,17512.16,3244.15,0.00,0.0,3,0.00,0.0,20756.31
957819,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2024-07-31,2,1,0,0,0,0,3,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,17512.16,3244.15,0.00,0.0,3,0.00,0.0,20756.31
1078222,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2024-08-31,2,1,0,0,0,0,3,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,17512.16,3244.15,0.00,0.0,3,0.00,0.0,20756.31
1199420,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2024-09-30,2,1,0,0,0,0,3,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,17218.32,3011.78,0.00,0.0,3,0.00,0.0,20230.10
1320617,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2024-10-31,2,1,0,0,0,0,3,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,17218.32,3011.78,0.00,0.0,3,0.00,0.0,20230.10
1442298,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2024-11-30,2,1,0,0,0,0,3,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,17143.40,3272.10,0.00,0.0,3,0.00,0.0,20415.50
1564571,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2024-12-31,2,1,0,0,0,0,3,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,17067.34,3158.29,0.00,0.0,3,0.00,0.0,20225.63
1686627,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2025-01-31,2,1,0,0,0,0,3,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,16991.81,2885.36,0.00,0.0,3,0.00,0.0,19877.17
1809009,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2025-02-28,2,1,0,0,0,0,3,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,16914.79,2949.03,0.00,0.0,3,0.00,0.0,19863.82
1931463,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2025-03-31,2,1,0,0,0,0,3,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,16838.63,2990.12,0.00,0.0,3,0.00,0.0,19828.75
2054048,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2025-04-30,2,1,0,0,0,0,3,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,16759.90,2757.52,0.00,0.0,3,0.00,0.0,19517.42
2176982,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2025-05-31,2,1,0,0,0,0,3,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,16682.17,2712.68,0.00,0.0,3,0.00,0.0,19394.85
2300219,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2025-06-30,2,1,0,0,0,0,3,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,16602.33,2590.96,0.00,0.0,3,0.00,0.0,19193.29
2423699,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2025-07-31,2,1,0,0,0,0,3,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,16522.47,2666.02,0.00,0.0,3,0.00,0.0,19188.49
2546132,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2025-08-31,2,1,0,0,0,0,3,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,16442.01,2689.23,0.00,0.0,3,0.00,0.0,19131.24
2669167,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2025-09-30,2,1,0,0,0,0,3,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,16361.05,2890.43,0.00,0.0,3,0.00,0.0,19251.48
2791773,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2025-10-31,3,1,0,0,0,0,4,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,20351.05,2990.38,0.00,0.0,4,0.00,0.0,23341.43
2913784,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2025-11-30,3,1,0,0,0,0,4,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,20319.04,3144.85,0.00,0.0,4,0.00,0.0,23463.89
3034920,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2025-12-31,3,1,0,0,0,0,4,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,20193.99,3057.11,0.00,0.0,4,0.00,0.0,23251.10
119090,ffff943c736f98d4840f65328ba372a29689312dd781b4...,2023-12-31,1,3,1,0,0,0,5,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,2272.16,2088.13,18144.16,0.0,5,0.00,0.0,22504.45
238476,ffff943c736f98d4840f65328ba372a29689312dd781b4...,2024-01-31,1,3,1,0,0,0,5,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,2291.34,2439.24,18144.16,0.0,5,0.00,0.0,22874.74
357729,ffff943c736f98d4840f65328ba372a29689312dd781b4...,2024-02-29,1,5,1,0,0,0,7,116.84,75.84,0.00,0.0,0.0,0.0,0.0,0.0,2322.45,2512.05,18040.69,0.0,7,192.68,0.0,22875.19
477209,ffff943c736f98d4840f65328ba372a29689312dd781b4...,2024-03-31,1,5,1,0,0,0,7,234.93,154.73,104.30,0.0,0.0,0.0,0.0,0.0,2341.30,4605.99,18555.47,0.0,7,493.96,0.0,25502.76
597134,ffff943c736f98d4840f65328ba372a29689312dd781b4...,2024-04-30,1,5,1,0,0,0,7,366.40,321.63,209.43,0.0,0.0,0.0,0.0,0.0,2372.98,4733.47,18830.21,0.0,7,897.46,0.0,25936.66
717014,ffff943c736f98d4840f65328ba372a29689312dd781b4...,2024-05-31,1,5,1,0,0,0,7,498.70,480.97,315.41,0.0,0.0,0.0,0.0,0.0,2404.92,4827.76,19103.31,0.0,7,1295.08,0.0,26335.99
837417,ffff943c736f98d4840f65328ba372a29689312dd781b4...,2024-06-30,1,4,1,0,0,0,6,2437.28,748.84,422.23,0.0,0.0,0.0,0.0,0.0,2437.28,5024.58,18581.09,0.0,6,3608.35,0.0,26042.95
957820,ffff943c736f98d4840f65328ba372a29689312dd781b4...,2024-07-31,1,4,1,0,0,0,6,2437.28,748.84,422.23,0.0,0.0,0.0,0.0,0.0,2437.28,5024.58,18581.09,0.0,6,3608.35,0.0,26042.95
1078223,ffff943c736f98d4840f65328ba372a29689312dd781b4...,2024-08-31,1,4,1,0,0,0,6,2437.28,748.84,422.23,0.0,0.0,0.0,0.0,0.0,2437.28,5024.58,18581.09,0.0,6,3608.35,0.0,26042.95
2546133,ffff943c736f98d4840f65328ba372a29689312dd781b4...,2025-08-31,0,3,1,0,0,0,4,0.00,1812.86,18040.69,0.0,0.0,0.0,0.0,0.0,0.00,1819.49,19534.81,0.0,4,19853.55,0.0,21354.30

### 3.5. Data Aggregation

In [16]:
def moda(series):
    m = series.mode()
    return m.iloc[0] if not m.empty else np.nan

In [17]:
#aggregating CRC's variables 
CRC_agg = (
    CRC
    .groupby("CONTRIB", as_index=True)
    .agg(
        count_cl_mean=("COUNT_CL", "mean"),
        #count_cl_mode=("COUNT_CL", moda),
        #count_cp_mean=("COUNT_CP", "mean"),
        #count_cp_mode=("COUNT_CP", moda),
        #count_auto_mean=("COUNT_AUTO", "mean"),
        #count_auto_mode=("COUNT_AUTO", moda),
        #count_ht_mean=("COUNT_HT", "mean"),
        #count_ht_mode=("COUNT_HT", moda),
        #count_conexo_mean=("COUNT_CONEXO", "mean"),
        #count_conexo_mode=("COUNT_CONEXO", moda),
        #count_other_mean=("COUNT_OTHER", "mean"),
        #count_other_mode=("COUNT_OTHER", moda),
        montvenc_cl_mean= ("MONTVENC_CL", "mean"),
        #montvenc_cl_mode= ("MONTVENC_CL", moda),
        #montvenc_cp_mean= ("MONTVENC_CP", "mean"),
        #montvenc_cp_mode= ("MONTVENC_CP", moda),
        #montvenc_auto_mean= ("MONTVENC_AUTO", "mean"),
        #montvenc_auto_mode= ("MONTVENC_AUTO", moda),
        #montvenc_ht_mean= ("MONTVENC_HT", "mean"),
        #montvenc_ht_mode= ("MONTVENC_HT", moda),
        montabatv_cl_mean= ("MONTABATV_CL", "mean"),
        #montabatv_cl_mode= ("MONTABATV_CL", moda),
        #montabatv_cp_mean= ("MONTABATV_CP", "mean"),
        #montabatv_cp_mode= ("MONTABATV_CL", moda),
        #montabatv_auto_mean= ("MONTABATV_AUTO", "mean"),
        #montabatv_auto_mode= ("MONTABATV_AUTO", moda),
        #montabatv_ht_mean= ("MONTABATV_HT", "mean"),
        #montabatv_ht_mode= ("MONTABATV_HT", moda),
        #balance_cl_mean=("BALANCE_CL", "mean"),
        #balance_cl_mode=("BALANCE_CL", moda),
        #balance_cp_mean=("BALANCE_CP", "mean"),
        #balance_cp_mode=("BALANCE_CP", moda),
        #balance_auto_mean=("BALANCE_AUTO", "mean"),
        #balance_auto_mode=("BALANCE_AUTO", moda),
        #balance_ht_mean=("BALANCE_HT", "mean"),
        #balance_ht_mode=("BALANCE_HT", moda),
        dividas_cl_mean=("DIVIDAS_CL", "mean"),
        #dividas_cl_mode=("DIVIDAS_CL", moda),
        #dividas_cp_mean=("DIVIDAS_CP", "mean"),
        #dividas_cp_mode=("DIVIDAS_CP", moda),
        #dividas_auto_mean=("DIVIDAS_AUTO", "mean"),
        #dividas_auto_mode=("DIVIDAS_AUTO", moda),
        #dividas_ht_mean=("DIVIDAS_HT", "mean"),
        #dividas_ht_mode=("DIVIDAS_HT", moda),
        subcount_total_mean=("SUBCOUNT_TOTAL", "mean"),
        montenc_total_mean=("MONTVENC_TOTAL", "mean"),
        montabatv_total_mean=("MONTABATV_TOTAL", "mean"),
        dividas_total_mean=("DIVIDAS_TOTAL", "mean") 
              
    )
)

In [18]:
#has the client default history?
CRC_agg['HIGH_RISK_CURRENT'] = (
    (CRC_agg['montenc_total_mean'] > 0) | 
    (CRC_agg['montabatv_total_mean'] > 0)
).astype(int)

In [19]:
CRC_agg[CRC_agg['HIGH_RISK_CURRENT'] == 1].count()

count_cl_mean           32098
montvenc_cl_mean        32098
montabatv_cl_mean       32098
dividas_cl_mean         32098
subcount_total_mean     32098
montenc_total_mean      32098
montabatv_total_mean    32098
dividas_total_mean      32098
HIGH_RISK_CURRENT       32098
dtype: int64

In [20]:
CRC_agg.head()

,count_cl_mean,montvenc_cl_mean,montabatv_cl_mean,dividas_cl_mean,subcount_total_mean,montenc_total_mean,montabatv_total_mean,dividas_total_mean,HIGH_RISK_CURRENT
CONTRIB,,,,,,,,,
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981,0.36,0.00000,0.0,2565.793600,5.28,0.000000,0.0,17196.20760,0
0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,4.32,0.00000,0.0,26448.032000,9.72,0.000000,0.0,34000.14920,0
0000f858346061c53064586a3347b34659565a6712d004e64309c2473f76faed,1.04,0.00000,0.0,2082.786000,8.32,0.000000,0.0,93756.88440,0
00025459b703e1c308553e83a6d545a71fe6a787c2dd1c62d26faa0207cc5b08,3.0,0.00000,0.0,22980.086400,4.28,0.000000,0.0,23082.37120,0
00041ebafb1270a818c30cb1fb20d3699002196644ea8fd9df9425df6f49db00,9.75,2416.34125,0.0,55289.663333,13.625,4038.840833,0.0,60154.73875,1

<div class="alert alert-block alert-info">

<a class="anchor" id="2. Data Exploration">    </a>
# CREDSCORE Dataset
       
</div>

**METADATA**:
- *sys_numero_submissao*: Submission number. 
- *sys_data_procura*: Date of risk probing.
- *kp_sqe*: Risk score of known customers based on behavior: A-X, A is better, null= unknown.
- *ks_score_tier*: risk score for granting (all customers) lower is better.

<a class="anchor" id="2.2 Analysing the Data">

## 2. Analysing the Data
    
</a>

### 2.1. Data Overview

In [ ]:
CREDSCORE.info()

In [ ]:
CREDSCORE.describe().round(2)

In [ ]:
#descriptive statistics for categorical data
CREDSCORE.describe(include = ['O'])

In [ ]:
#how many clients exists for each classification (Alphabetical order)
CREDSCORE['kp_sqe'] \
    .value_counts(dropna=False) \
    .sort_index()

- We can see the most common classification is 'A' which is a good indicator, and there is no client with classification 'X' (the worst)
- We should see what classification is considered risky

In [ ]:
CREDSCORE['ks_score_tier'].value_counts(dropna=False)

- The most common one is 1, which is also a good indicator.

### 2.2. Checking Duplicates

In [ ]:
#checking number of duplicates
CREDSCORE.duplicated().sum()

In [ ]:
dups = CREDSCORE[CREDSCORE.duplicated(subset=["CONTRIB"], keep=False)].sort_values("CONTRIB")
display(dups.head(20))

In [ ]:
CREDSCORE = CREDSCORE.sort_values(['CONTRIB'])

In [ ]:
import pandas as pd

# Show all columns
pd.set_option('display.max_columns', None)

# Show full content of each column (no truncation)
pd.set_option('display.max_colwidth', None)

# Optional: increase display width for better readability
pd.set_option('display.width', 200)

# Display the first 10 duplicated rows sorted by 'CONTRIB'
duplicated_rows = CREDSCORE[CREDSCORE.duplicated()]
duplicated_rows.sort_values(['CONTRIB']).head(10)

### 2.3. Checking Incoherencies

In [ ]:
print("shape:", CREDSCORE.shape)
print("clientes únicos:", CREDSCORE['CONTRIB'].nunique())
print("duplicados por cliente:", CREDSCORE.duplicated(subset=['CONTRIB']).sum())

- There are 700 duplicates in *CONTRIB*

In [ ]:
CREDSCORE['sys_data_procura'] = pd.to_datetime(CREDSCORE['sys_data_procura'], errors='coerce')

# número de datas diferentes por cliente
dates_per_client = CREDSCORE.groupby('CONTRIB')['sys_data_procura'].nunique()

print("Clients with >1 date:", (dates_per_client > 1).sum())

- There are 106 clients that have more than 1 date, which is not possible because in this dataset we are only considering the date of client's last credit proposal.

In [ ]:
CREDSCORE[CREDSCORE['CONTRIB']=='0327b5a9a23ce7ae7b9256d3d823ad083b8f499400d8b9fcc73203df81780557']

### 2.4. Checking Missing Values

In [ ]:
CREDSCORE['kp_sqe'] = CREDSCORE['kp_sqe'].astype(str).str.strip().str.upper()
CREDSCORE['kp_sqe'] = CREDSCORE['kp_sqe'].replace({'NULL': np.nan, 'NONE': np.nan})

In [ ]:
#checking umber of missing values in each column as a percentage
CREDSCORE.isna().sum()/len(CREDSCORE) * 100

In [ ]:
#checking number of missing values
CREDSCORE.isna().sum()

- This missing values correspond to unknown clients.

### 2.5. Checking Outliers

In [ ]:
metric_features= ['ks_score_tier']

In [ ]:
def plot_boxplot(data, feat='ks_score_tier', title="Box Plot (>0 only)"):
    
    # Keep only values strictly greater than 0
    values = data[feat]
    values = values[(values > 0) & (values.notna())]
    
    plt.figure(figsize=(6, 4.5))
    
    if len(values) > 0:
        sns.boxplot(x=values)
        plt.title(feat, fontsize=10)
    else:
        plt.title(f"{feat} (no >0 values)", fontsize=10)
    
    plt.suptitle(title, fontsize=16)
    plt.tight_layout()
    plt.show()

In [ ]:
#applying the function to our numerical features
plot_boxplot(CREDSCORE)

In [ ]:
CREDSCORE[CREDSCORE['ks_score_tier'] > 4].count()

### 2.6. Checking Distribution

#### 2.6.1. Numerical Variable

In [ ]:
df= pd.DataFrame(CREDSCORE[metric_features])

In [ ]:
# Sampling
N = min(200_000, len(CREDSCORE))
sample = CREDSCORE.sample(n=N, random_state=42)

col = metric_features[0]   # 'ks_score_tier'

fig, ax = plt.subplots(figsize=(7, 5))

sns.histplot(sample[col].dropna(), bins=60, kde=False, ax=ax)

ax.set_title(col, fontsize=12)
ax.set_ylabel("Frequency")

plt.tight_layout()
plt.show()

#### 2.6.2. Categorical Variable

In [ ]:
'''import matplotlib.pyplot as plt
import seaborn as sns

# Set white background style
sns.set_style('white')

# Function to generate a palette based on number of unique categories
def get_palette(CREDSCORE, column):
    n = CREDSCORE[column].nunique()
    return sns.color_palette("tab20", n) if n <= 20 else sns.color_palette("husl", n)

# Specify the variable to plot
column_to_plot = 'kp_sqe'  # replace with your actual column name

# Generate palette
palette = get_palette(CREDSCORE, column_to_plot)

# Create figure
plt.figure(dpi=300, figsize=(12, 6))
plt.gcf().patch.set_facecolor('white')

# Create count plot
sns.countplot(
    data=CREDSCORE,
    x=column_to_plot,
    hue=column_to_plot,
    palette=palette,
    dodge=False
)

# Rotate x-axis labels for readability
plt.xticks(rotation=90)

# Remove legend (optional)
plt.legend([],[], frameon=False)

# Adjust layout
plt.tight_layout()

# Show plot
plt.show()'''

In [ ]:
# Set white background style
sns.set_style('white')

# Column to plot
column_to_plot = 'kp_sqe'  # replace if needed

# Count observations per category
counts = CREDSCORE[column_to_plot].value_counts().sort_index()

# Category with the highest number of observations
max_category = counts.idxmax()

# Define colors
default_color = "lightgray"
highlight_color = "steelblue"

# Create palette
palette = [
    highlight_color if cat == max_category else default_color
    for cat in counts.index
]

# Plot
plt.figure(dpi=300, figsize=(12,6))
plt.gcf().patch.set_facecolor('white')

sns.barplot(
    x=counts.index,
    y=counts.values,
    palette=palette
)

# Rotate labels
plt.xticks(rotation=90)

# Layout
plt.tight_layout()

# Show
plt.show()

<a class="anchor" id="2.2 Analysing the Data">

## 3. Data Preparation
    
</a>

### 3.1. Handling Incoherencies

- Keeping only the last line (the most recent date) for each client.

In [21]:
CREDSCORE = CREDSCORE.sort_values(['CONTRIB','sys_data_procura'])
CREDSCORE = CREDSCORE.groupby('CONTRIB', as_index=False).tail(1)

In [22]:
print("shape:", CREDSCORE.shape)
print("clientes únicos:", CREDSCORE['CONTRIB'].nunique())
print("duplicados por cliente:", CREDSCORE.duplicated(subset=['CONTRIB']).sum())

shape: (62173, 5)
clientes únicos: 62173
duplicados por cliente: 0

In [23]:
# remover colunas técnicas
CREDSCORE = CREDSCORE.drop(columns=['sys_numero_submissao','sys_data_procura'], errors='ignore')

In [24]:
CREDSCORE.groupby(CREDSCORE['kp_sqe'].isna())['ks_score_tier'].describe()

          count      mean       std  min  25%  50%  75%  max
kp_sqe
False   44389.0  1.462119  0.736990  1.0  1.0  1.0  2.0  5.0
True    17784.0  1.843848  0.941085  1.0  1.0  2.0  3.0  5.0

- To analyse the *ks_score_tier* of the values with and without *kp_sqe* (tue= with missing values).
- In average, the clients with missing values have the average of the highest score, which means higher risk (as the company has less trust in them, it assumes higher incertainty).

### 3.2. Removing Duplicates

In [25]:
#droping duplicate rows 
CREDSCORE = CREDSCORE.drop_duplicates()

In [26]:
for col in CREDSCORE.columns:
    print(f"'{col}'")

'CONTRIB'
'kp_sqe'
'ks_score_tier'

In [ ]:
'''CREDSCORE['sys_data_procura'] = pd.to_datetime(CREDSCORE['sys_data_procura'])

CREDSCORE = CREDSCORE.loc[
    CREDSCORE.groupby('CONTRIB')['sys_data_procura'].idxmax()
]

print(CREDSCORE)'''

### 3.3. Handling Missing Values

In [27]:
#filling missing values
CREDSCORE['kp_sqe'] = CREDSCORE['kp_sqe'].fillna('NO_BEHAVIOR_HISTORY')

### 3.4. Handling Outliers

In [ ]:
#CREDSCORE['ks_score_tier'] = CREDSCORE['ks_score_tier'].clip(upper=4)

### 3.5. Feature Engineering

In [28]:
#creating is_risky 
CREDSCORE['is_risky'] = (
    (CREDSCORE['kp_sqe'] > 'D') |
    (CREDSCORE['ks_score_tier'] > 2)
)

In [29]:
CREDSCORE['is_risky'].value_counts(dropna=False)

is_risky
True     42297
False    19876
Name: count, dtype: int64

In [30]:
CREDSCORE.head()

,CONTRIB,kp_sqe,ks_score_tier,is_risky
0,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,H,2.0,True
1,0000ab2116257783438c70ff85a3e98f2d4194ebe53434...,D,1.0,False
2,00041ebafb1270a818c30cb1fb20d3699002196644ea8f...,F,3.0,True
3,00050fe9f0e69ce221a574af0baaff0b37c598af7a5cc6...,A,1.0,False
4,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a9...,H,1.0,True

<div class="alert alert-block alert-info">

<a class="anchor" id="2. Data Exploration">    </a>
# FAMA Dataset
       
</div>

**METADATA**
- *Date_Obs*: Observation Date (MMYY).
- *ALLBD_N_Dossiers__N*: Distinct count of Dossiers.
- *ALLBD_N_CL__N*: Distinct count of Dossiers for CL.
- *ALLBD_N_CP__N*: Distinct count of Dossiers for CP.
- *ALLBD_A_CL__N*: Distinct count of Dossiers for active CL.
- *ALLBD_A_CP__N*: Distinct count of Dossiers for active CP.
- *ALLBD_MTFINO_CL__N*: Number financings on CL - Total ammount.
- *ALLBD_MTFINO_CP__N*: Number financings on CP -Total ammount.
- *ALLBD_MTFIN_CL__N*: Presently financed on CL -present.
- *ALLBD_MTFIN_CP__N*: presently financed on CP -present.
- *ALLBD_IDADE_MSA__N*: max antiquity of contracts.
- *ALLBD_IDADE_MIN__N*: min antiquity of contracts.
- *ALLBD_IDADE_MEAN__N*: mean antiquity of contracts.
- *ALLBD_SUM_NUMFIN_CP__N*: Number Financings on CP  -lifetime.
- *ALLBD_mean_active_resso__N*: Average income from active contracts.
- *ALLBD_max_active_resso__N*: Maximum income from active contracts.
- *ALLBD_mean_duration_CL__N*: Average duration of CL contracts.
- *ALLBD_mean_lifecycle_CL__N*: Average lifecycle by duration on CL.
- *ALLBD_N_events__N*: Number of Contracts changes.
- *sdem_SITFAM*: Family Situation (C – married, D – divorced, S – single, U – cohabiting / partnered, V – widowed, X – other).
- *sdem_HABITAT*: Housing Situation (A – Access to property (loan), E – Housed by the employer (workplace), F – Housed by family, L – Tenant (rental), O – Other, P – Owner, X – Unknown). 
- *sdem_age*: Client's age.

### 2.1. Data Overview

Neste dataset vamos olhar para o historico do cliente e nao para o que esta ativo.

In [ ]:
FAMA.info()

In [ ]:
num_cols = FAMA.select_dtypes(include=['number']).columns
obj_cols = FAMA.select_dtypes(include=['object']).columns

print("Numerical:", len(num_cols))
print("Categorical:", len(obj_cols))

In [ ]:
pd.set_option('display.max_columns', None)
FAMA.head()

In [ ]:
FAMA.describe().T

In [ ]:
#descriptive statistics for categorical data
FAMA.describe(include = ['O'])

In [ ]:
FAMA.shape

In [ ]:
FAMA['CONTRIB'].nunique()

In [ ]:
FAMA['sdem_SITFAM'].value_counts(dropna=False)

- There are a large number of married (C), other (X), single (S) and cohabiting (U) people. 
- The least common are widowed

In [ ]:
FAMA['sdem_HABITAT'].value_counts(dropna=False)

- Most people have access to property (loan), are housed by family and owned or rent a house.
- The least common is 'other' and housed by the employer.

### 2.2. Checking Duplicates

In [ ]:
#checking number of duplicates
FAMA.duplicated().sum()

### 2.3. Checking Missing Values

In [ ]:
#checking number of missing values
FAMA.isna().sum()

### 2.4. Checking Outliers

In [ ]:
def plot_multiple_boxplots(data, feats, n_cols=3, title="Numeric Variables' Box Plots (>0 only)"):
    
    n_rows = ceil(len(feats) / n_cols)
    
    fig, axes = plt.subplots(
        n_rows,
        n_cols,
        figsize=(6 * n_cols, 4.5 * n_rows)
    )
    
    axes = axes.flatten()
    
    for i, feat in enumerate(feats):
        
        # Keep only values strictly greater than 0
        values = data[feat]
        values = values[(values > 0) & (values.notna())]
        
        if len(values) > 0:
            sns.boxplot(x=values, ax=axes[i])
            axes[i].set_title(feat, fontsize=10)
        else:
            axes[i].set_title(f"{feat} (no >0 values)", fontsize=10)
    
    # Remove unused subplots
    for j in range(len(feats), len(axes)):
        fig.delaxes(axes[j])
    
    plt.suptitle(title, fontsize=18)
    plt.tight_layout(rect=[0, 0, 1, 0.97])
    plt.show()

In [ ]:
plot_multiple_boxplots(FAMA, num_cols)

In [ ]:
FAMA[FAMA['ALLBD_N_Dossiers__N'] > 70].count()

In [ ]:
FAMA[FAMA['ALLBD_N_CL__N'] > 55].count()

In [ ]:
FAMA[FAMA['ALLBD_N_CP__N'] > 30].count()

In [ ]:
FAMA[FAMA['ALLBD_A_CL__N'] > 4].count()

In [ ]:
FAMA[FAMA['ALLBD_A_CP__N'] > 5].count()

In [ ]:
FAMA[FAMA['ALLBD_MTFINO_CL__N'] > 250000].count()

In [ ]:
FAMA[FAMA['ALLBD_MTFINO_CP__N'] > 150000].count()

In [ ]:
FAMA[FAMA['ALLBD_MTFIN_CL__N'] > 250000].count()

In [ ]:
FAMA[FAMA['ALLBD_MTFIN_CP__N'] > 4000].count()

In [ ]:
FAMA[FAMA['ALLBD_IDADE_MSA__N'] > 10000].count()

In [ ]:
FAMA[FAMA['ALLBD_SUM_NUMFIN_CP__N'] > 3000].count()

In [ ]:
FAMA[FAMA['ALLBD_mean_active_resso__N'] > 10000].count()

In [ ]:
FAMA[FAMA['ALLBD_max_active_resso__N'] > 15000].count()

In [ ]:
FAMA[FAMA['ALLBD_mean_lifecycle_CL__N'] > 1].count()

In [ ]:
FAMA[FAMA['ALLBD_N_events__N'] > 70].count()

In [ ]:
FAMA[FAMA['sdem_age'] > 85].count()

### 2.5. Checking Distribution

#### 2.5.1. Numerical Variables

In [ ]:
df= pd.DataFrame(FAMA[num_cols])

In [ ]:
# Sampling
N = 200_000
sample = FAMA.sample(n=min(N, len(FAMA)), random_state=42)

cols = sample.select_dtypes(include=[np.number]).columns  # all 20 variables

plots_per_fig = 6   # 2 rows x 3 cols
n_figs = ceil(len(cols) / plots_per_fig)

for f in range(n_figs):
    
    start = f * plots_per_fig
    end = start + plots_per_fig
    subset_cols = cols[start:end]
    
    fig, axes = plt.subplots(2, 3, figsize=(14, 8))
    axes = axes.ravel()
    
    for ax, col in zip(axes, subset_cols):
        sns.histplot(sample[col].dropna(), bins=60, kde=False, ax=ax)
        ax.set_title(col, fontsize=10)
    
    # Remove empty subplots if last figure has fewer than 6 plots
    for j in range(len(subset_cols), len(axes)):
        fig.delaxes(axes[j])
    
    plt.tight_layout()
    plt.show()

#### 2.5.2. Categorical Variables

In [ ]:
# Set white background style
sns.set_style('white')


# Loop through each variable
for column in obj_cols:
    
    # Count observations per category
    counts = CREDSCORE[column].value_counts().sort_index()

    # Category with the highest number of observations
    max_category = counts.idxmax()

    # Define colors
    default_color = "lightgray"
    highlight_color = "steelblue"

    # Create palette
    palette = [
        highlight_color if cat == max_category else default_color
        for cat in counts.index
    ]

    # Plot
    plt.figure(dpi=300, figsize=(12,6))
    plt.gcf().patch.set_facecolor('white')

    sns.barplot(
        x=counts.index,
        y=counts.values,
        palette=palette
    )

    # Title
    plt.title(f'Distribution of {column}')

    # Rotate labels
    plt.xticks(rotation=90)

    # Layout
    plt.tight_layout()

    # Show
    plt.show()

In [ ]:
# Set white background style
sns.set_style("white")

# Create subplots
fig, axes = plt.subplots(1, len(obj_cols), figsize=(18,5), dpi=300)

# Ensure axes is iterable if only one plot
if len(obj_cols) == 1:
    axes = [axes]

for ax, column in zip(axes, obj_cols):

    counts = CREDSCORE[column].value_counts()
    max_category = counts.idxmax()

    # Create palette
    palette = {
        cat: "steelblue" if cat == max_category else "lightgray"
        for cat in CREDSCORE[column].dropna().unique()
    }

    sns.countplot(
        data=CREDSCORE,
        x=column,
        palette=palette,
        order=sorted(CREDSCORE[column].dropna().unique()),
        ax=ax
    )

    ax.set_title(f'Distribution of {column}')
    ax.tick_params(axis='x', rotation=90)

# Layout
plt.tight_layout()
plt.show()

### 2.6. Checking Correlation between variables

In [ ]:
#checking correlation between variables 
#we are going to use spearman correlation since our variables do not follow a normal distribution
cor_spearman = FAMA[num_cols].corr(method ='spearman')
cor_spearman

In [ ]:
#creating correlation matrix to facilitate interpretation
def cor_heatmap(cor):
    
    #setting the figure size
    plt.figure(figsize=(12, 10))

    #creating a mask for the upper triangle of the matrix (to avoid plotting duplicate correlation values)
    mask = np.triu(np.ones_like(cor, dtype=bool))

    #plotting the correlation heatmap
    sns.heatmap(
        data=cor,                 #correlation matrix input
        mask=mask,                #applying upper-triangle mask
        annot=True,               #displaying correlation coefficients
        cmap='YlGnBu',            #color map for visual contrast
        fmt='.2f',                #formatting values to two decimals
        square=True,              #ensuring square-shaped cells
        linewidths=0.5,           #adding grid lines between cells
        cbar_kws={"shrink": 0.8}  #adjusting color bar size
    )

    #adding a title and display the plot
    plt.title("Spearman Correlation Matrix", fontsize=14)
    plt.show()

'''This function visualises a correlation matrix using a heatmap to
facilitate interpretation of relationships between variables. By 
masking the upper triangle of the matrix, the plot avoids redundant
information and improves the readability. '''

In [ ]:
#applying the function to our numerical features
cor_heatmap(cor_spearman)

**Redundant Variables**:
- *ALLBD_N_CL__N* vs *ALLBD_N_Dossiers__N* (0.93)
- *ALLBD_N_Dossiers__N* vs *ALLBD_N_events__N* (1.00)
- *ALLBD_N_events__N* vs *ALLBD_N_CL__N* (0.93)

<a class="anchor" id="2.2 Analysing the Data">

## 3. Data Preparation
    
</a>

### 3.1. Handling Outliers

In [31]:
FAMA['ALLBD_N_Dossiers__N'] = FAMA['ALLBD_N_Dossiers__N'].clip(upper=70)
FAMA['ALLBD_N_CL__N'] = FAMA['ALLBD_N_CL__N'].clip(upper=55)
FAMA['ALLBD_N_CP__N'] = FAMA['ALLBD_N_CP__N'].clip(upper=30)
FAMA['ALLBD_A_CL__N'] = FAMA['ALLBD_A_CL__N'].clip(upper=4)
FAMA['ALLBD_A_CP__N'] = FAMA['ALLBD_A_CP__N'].clip(upper=5)
FAMA['ALLBD_MTFINO_CL__N'] = FAMA['ALLBD_MTFINO_CL__N'].clip(upper=250000)
FAMA['ALLBD_MTFINO_CP__N'] = FAMA['ALLBD_MTFINO_CP__N'].clip(upper=150000)
FAMA['ALLBD_MTFIN_CL__N'] = FAMA['ALLBD_MTFIN_CL__N'].clip(upper=250000)
FAMA['ALLBD_MTFIN_CP__N'] = FAMA['ALLBD_MTFIN_CP__N'].clip(upper=4000)
FAMA['ALLBD_IDADE_MSA__N'] = FAMA['ALLBD_IDADE_MSA__N'].clip(upper=10000)
FAMA['ALLBD_SUM_NUMFIN_CP__N'] = FAMA['ALLBD_SUM_NUMFIN_CP__N'].clip(upper=3000)
FAMA['ALLBD_mean_active_resso__N'] = FAMA['ALLBD_mean_active_resso__N'].clip(upper=10000)
FAMA['ALLBD_max_active_resso__N'] = FAMA['ALLBD_max_active_resso__N'].clip(upper=15000)
FAMA['ALLBD_mean_lifecycle_CL__N'] = FAMA['ALLBD_mean_lifecycle_CL__N'].clip(upper=1)
FAMA['ALLBD_N_events__N'] = FAMA['ALLBD_N_events__N'].clip(upper=70)
FAMA['sdem_age'] = FAMA['sdem_age'].clip(upper=85)

### 3.2. Feature Engineering

In [32]:
# proporção de créditos ativos

FAMA["active_credit_ratio"] = (
    FAMA["ALLBD_A_CL__N"] + FAMA["ALLBD_A_CP__N"]
) / (
    FAMA["ALLBD_N_CL__N"] + FAMA["ALLBD_N_CP__N"] + 1
)

In [33]:
FAMA.head()

,CONTRIB,Date_Obs,ALLBD_N_Dossiers__N,ALLBD_N_CL__N,ALLBD_N_CP__N,ALLBD_A_CL__N,ALLBD_A_CP__N,ALLBD_MTFINO_CL__N,ALLBD_MTFINO_CP__N,ALLBD_MTFIN_CL__N,ALLBD_MTFIN_CP__N,ALLBD_IDADE_MSA__N,ALLBD_IDADE_MIN__N,ALLBD_IDADE_MEAN__N,ALLBD_SUM_NUMFIN_CP__N,ALLBD_mean_active_resso__N,ALLBD_max_active_resso__N,ALLBD_mean_duration_CL__N,ALLBD_mean_lifecycle_CL__N,ALLBD_N_events__N,sdem_SITFAM,sdem_HABITAT,sdem_age,active_credit_ratio
0,31f4b2a40e2cc73faf9cf16c7bd6ebeea6f322931d4e0b...,2024-11-30,15.0,6.0,9.0,1.0,0.0,88784.04,0.00,88784.040000,0.0,4443.0,-808.0,1280.533333,0.0,1153.000000,1153.0,120.0,0.425000,15.0,C,P,62,0.062500
1,bb7bc8dfa33e27eb832f58210a2d3282839cd2a8e7f420...,2024-11-30,6.0,4.0,2.0,1.0,2.0,9584.91,7628.41,9584.910000,0.0,3120.0,-2077.0,466.333333,14.0,1564.666667,1582.0,72.0,0.138889,6.0,C,A,65,0.428571
2,a377de96fc89a1aabdb5e25682e54c7d02a7209c7246d0...,2024-11-30,8.0,5.0,3.0,1.0,0.0,22000.86,0.00,22000.860000,0.0,4936.0,-2089.0,907.625000,0.0,1765.000000,1765.0,36.0,0.277778,8.0,C,L,65,0.111111
3,9e4d032b84105ac4981257fc993ed33f60dfec1542c723...,2024-11-30,3.0,3.0,0.0,1.0,0.0,10384.00,0.00,10384.000000,0.0,2882.0,-2096.0,301.000000,0.0,840.000000,840.0,72.0,0.138889,3.0,V,P,69,0.250000
4,7d0cb0079863cbf9d6d179491aab944c9af7e988d1e4bc...,2024-11-30,9.0,8.0,1.0,1.0,0.0,12866.23,0.00,13756.584246,0.0,8629.0,-1063.0,2267.555556,0.0,3268.000000,3268.0,48.0,0.916667,9.0,C,A,68,0.100000

In [34]:
# carga financeira (montante de crédito vs rendimento)
'''FAMA["debt_income_ratio"] = (
    FAMA["ALLBD_MTFIN_CL__N"] /
    (FAMA["ALLBD_mean_active_resso__N"] + 1)
)'''

'FAMA["debt_income_ratio"] = (\n    FAMA["ALLBD_MTFIN_CL__N"] /\n    (FAMA["ALLBD_mean_active_resso__N"] + 1)\n)'

In [ ]:
# ratio de progresso do crédito

'''FAMA["credit_progress"] = (
    FAMA["ALLBD_MTFIN_CL__N "] /
    (FAMA["ALLBD_MTFINO_CL__N "] + 1)
)'''

In [ ]:
# percentagem de credito por pagar

'''FAMA["credit_remaining_ratio"] = (
    FAMA["ALLBD_MTFIN_CL__N"] /
    (FAMA["ALLBD_MTFINO_CL__N"] + 1)
)'''

In [35]:
drop=['Date_Obs', 'ALLBD_N_Dossiers__N', 'ALLBD_N_CL__N', 
      'ALLBD_N_CP__N', 'ALLBD_A_CL__N', 'ALLBD_A_CP__N', 
      'ALLBD_MTFINO_CL__N', 'ALLBD_MTFINO_CP__N', 
      'ALLBD_MTFIN_CL__N', 'ALLBD_MTFIN_CP__N', 
      'ALLBD_IDADE_MSA__N', 'ALLBD_IDADE_MIN__N',
      'ALLBD_IDADE_MEAN__N', 'ALLBD_SUM_NUMFIN_CP__N', 
      'ALLBD_max_active_resso__N', 'ALLBD_mean_active_resso__N']
FAMA= FAMA.drop(columns=drop, errors='ignore')

- We have decided to drop these variables due to their amount of incoherencies and the redundance between some of them.

In [ ]:
FAMA.head()

<div class="alert alert-block alert-info">

<a class="anchor" id="2. Data Exploration">    </a>
# BDOSS Dataset
       
</div>

<a class="anchor" id="2.2 Analysing the Data">

## 2. Analysing the Data
    
</a>

**METADATA**
- *DOSSIER*: Dossier Number.
- *POLE*: Business unit (D - D & A; N - NCP; P - Direct).
- *TYPEPROD*: Product Type (CL - Classic; CP - Permanent Account).
- *PRODALP*: Product Type (AUR, AX7, B2K, BM7, etc).
- *BICONTRATO*: Co-signataries
- *POS*: Dossier classification (SOL – client settles on the contract‑termination date; SAN – client settles before that date).
- *OBS_DATE*: Observation Date.
- *DCREAT*: Dossier Creation Date.
- *DATFIN*: Last financing date.
- *D1FIN*: First financing date.
- *DPOS*: Dossier position date.
- *DURDEG*: Number of regularizations (instalments).
- *RANGPRO*: Number of regularizations payed.
- *RANGCLI*: Maximum number of monthly payment delays.
- *MTFINO*: Amount financed from dossier opening.
- *MTFIN*: Fiananced amount in dossier.
- *MENSALIDADE*: Monthly instalment.
- *MENSALIDADE_CORR*: Current Monthly instalment.
- *CRD*: Capital Amount still due.
- *SREC*: Outstanding Balance.
- *ACTIVIDADE_GLOBAL*: Dossier Global activity (Active; Ex-Active; Inactive).
- *RN*: How many times in the last 12 months a payment was not made in due time. 
- *RD*: Whenever a payment is not due in time, it takes more or less time to reciver, this isthe accumulated number of months that a payment took to be collected. 
- *RISK*: Chain with risk positions in last 24 months.
- *RISKA*: Dossier risk position on the last month.
- *AGFIN*: Financing agency.
- *PAGAMENTO*: Selected payment option for installments.
- *RESSO*: Wage of the contract’s primary holder.
- *CSP*: Socio‑professional code (10 – Merchants; 15 – Service Providers; 20 – Managing Partners/Partners; 30 – Private Directors – Senior Management; 31 – Private Department Heads – Middle Management; 40 – Public Directors – Senior Management; 41 – Public Department Heads – Middle Management; 60 – Office Employees – Commerce; 70 – Public Employees; 74 – Military/Police; 80 – Workers; 81 – Driver‑Security; 86 – Cleaning Staff; 90 – Retired Private‑Sector; 91 – Retired Public‑Sector; 92 – Unemployed/No Profession; 96 – Fixed‑term/Temporary Contractor; 99 – Indeterminate; 25 – Pension Income;
32 – Health Professional; 33 – Nurse; 34 – Doctor; 35 – Teacher).
- *DCSP*: Date of the socio‑professional code.
- *NATIO*: Nationality (C – European Union; D – Other; P – Portuguese; X – Unknown).
- *PTT*: Postal code. 
- *NBENF*: Number of dependents. 
- *MODCONTACTO*: Contact mode (A – Credscore; C – Mail; E – Outbound calls;
H – Homebanking; K – Click-to-call; M – Email; Q – Telematics; S – SMS; T – Telephone; V – Agency visit; W – Web telematics; X – Cetelem Center).

### 2.1. Data Overview

In [ ]:
BDOSS.info()

In [ ]:
pd.set_option('display.max_columns', None)
BDOSS.head()

In [ ]:
BDOSS.info()

In [ ]:
BDOSS.describe(include='all').T

### 2.2. Checking Duplicates

In [ ]:
BDOSS.duplicated().sum()

### 2.3. Checking Missing Values

In [ ]:
BDOSS.isna().sum()[BDOSS.isna().sum() > 0]

In [ ]:
#checking number of missing values in each column as a percentage
BDOSS.isna().sum()[BDOSS.isna().sum() > 0]/len(BDOSS) * 100

### 2.4. Checking Outliers

In [ ]:
num_cols_DB = BDOSS.select_dtypes(include=['number']).columns
obj_cols_DB = BDOSS.select_dtypes(include=['object']).columns

print("Numerical:", len(num_cols_DB))
print("Categorical:", len(obj_cols_DB))

In [ ]:
from math import ceil

def plot_multiple_boxplots(data, feats, n_cols=3, title="Numeric Variables' Box Plots"):
    
    n_rows = ceil(len(feats) / n_cols)
    
    fig, axes = plt.subplots(
        n_rows,
        n_cols,
        figsize=(6 * n_cols, 4.5 * n_rows)
    )
    
    axes = axes.flatten()
    
    for i, feat in enumerate(feats):
        
        # Keep all non-null values
        values = data[feat].dropna()
        
        if len(values) > 0:
            sns.boxplot(x=values, ax=axes[i])
            axes[i].set_title(feat, fontsize=10)
        else:
            axes[i].set_title(f"{feat} (no values)", fontsize=10)
    
    # Remove unused subplots
    for j in range(len(feats), len(axes)):
        fig.delaxes(axes[j])
    
    plt.suptitle(title, fontsize=18)
    plt.tight_layout(rect=[0, 0, 1, 0.97])
    plt.show()

In [ ]:
plot_multiple_boxplots(BDOSS, num_cols_DB)

In [ ]:
BDOSS[BDOSS['MTFINO'] > 80000].count()

In [ ]:
BDOSS[BDOSS['MTFIN'] > 80000].count()

In [ ]:
BDOSS[BDOSS['MENSALIDADE'] > 4000].count()

In [ ]:
BDOSS[BDOSS['CRD'] > 100000].count()

In [ ]:
BDOSS[BDOSS['SREC'] > 40000].count()

In [ ]:
BDOSS[BDOSS['RESSO'] > 700000].count()

In [ ]:
BDOSS[BDOSS['NBENF'] > 10].count()

### 2.5. Checking Distributions

#### 2.5.1. Numerical Variables

In [ ]:
df= pd.DataFrame(BDOSS[num_cols_DB])

In [ ]:
# Sampling (50k is usually enough for distributions)
N = 50_000
sample = BDOSS.sample(n=min(N, len(BDOSS)), random_state=42)

# Numeric columns
cols = sample.select_dtypes(include=[np.number]).columns

plots_per_fig = 6
n_figs = ceil(len(cols) / plots_per_fig)

for f in range(n_figs):

    start = f * plots_per_fig
    end = start + plots_per_fig
    subset_cols = cols[start:end]

    n_plots = len(subset_cols)
    n_rows = ceil(n_plots / 3)

    fig, axes = plt.subplots(n_rows, 3, figsize=(14, 4 * n_rows))
    axes = axes.flatten()

    for ax, col in zip(axes, subset_cols):
        values = sample[col].dropna().values
        sns.histplot(values, bins=50, ax=ax)
        ax.set_title(col, fontsize=10)

    # Remove unused axes
    for j in range(n_plots, len(axes)):
        fig.delaxes(axes[j])

    plt.tight_layout()
    plt.show()

#### 2.5.2. Categorical Variable

In [ ]:
sns.set_style("white")

plots_per_fig = 6
n_figs = ceil(len(obj_cols_DB) / plots_per_fig)

for f in range(n_figs):
    start = f * plots_per_fig
    end = start + plots_per_fig
    subset_cols = obj_cols_DB[start:end]

    n_plots = len(subset_cols)
    n_rows = ceil(n_plots / 3)

    fig, axes = plt.subplots(n_rows, 3, figsize=(14, 4*n_rows), dpi=150)
    axes = axes.flatten()

    for ax, col in zip(axes, subset_cols):
        counts = BDOSS[col].value_counts()
        max_category = counts.idxmax()

        colors = [
            "steelblue" if cat == max_category else "lightgray"
            for cat in counts.index
        ]

        ax.bar(counts.index.map(str), counts.values, color=colors)
        ax.set_title(col, fontsize=10)
        ax.tick_params(axis='x', rotation=90)

    # Remove empty axes
    for j in range(n_plots, len(axes)):
        fig.delaxes(axes[j])

    plt.tight_layout()
    plt.show()

### 2.6. Checking Correlation between variables

In [ ]:
#checking correlation between variables 
#we are going to use spearman correlation since our variables do not follow a normal distribution
cor_spearman = BDOSS[num_cols_DB].corr(method ='spearman')
cor_spearman

In [ ]:
#creating correlation matrix to facilitate interpretation
def cor_heatmap(cor):
    
    #setting the figure size
    plt.figure(figsize=(12, 10))

    #creating a mask for the upper triangle of the matrix (to avoid plotting duplicate correlation values)
    mask = np.triu(np.ones_like(cor, dtype=bool))

    #plotting the correlation heatmap
    sns.heatmap(
        data=cor,                 #correlation matrix input
        mask=mask,                #applying upper-triangle mask
        annot=True,               #displaying correlation coefficients
        cmap='YlGnBu',            #color map for visual contrast
        fmt='.2f',                #formatting values to two decimals
        square=True,              #ensuring square-shaped cells
        linewidths=0.5,           #adding grid lines between cells
        cbar_kws={"shrink": 0.8}  #adjusting color bar size
    )

    #adding a title and display the plot
    plt.title("Spearman Correlation Matrix", fontsize=14)
    plt.show()

'''This function visualises a correlation matrix using a heatmap to
facilitate interpretation of relationships between variables. By 
masking the upper triangle of the matrix, the plot avoids redundant
information and improves the readability. '''

In [ ]:
#applying the function to our numerical features
cor_heatmap(cor_spearman)

**Redundant Variables**:
- *MTFIN* vs *MTFINO* (1.00)
- *RN* vs *RD* (0.94)
- *MENSALIDADE* vs *MTFIN* AND *MTFINO* (0.88)

### 2.4. Checking Incoherencies

**- Constant Features**

In [ ]:
BDOSS['MENSALIDADE_CORR'].unique()

In [ ]:
BDOSS['ACTIVIDADE_GLOBAL'].unique()

In [ ]:
BDOSS['TYPEPROD'].unique()

In [ ]:
BDOSS['BICONTRATO'].unique()

**- more data analysis**

In [ ]:
BDOSS['RISK'].value_counts()

In [ ]:
BDOSS['RISKA'].value_counts()

In [ ]:
BDOSS['NBENF'].value_counts()

In [ ]:
BDOSS['AGFIN'].value_counts()

In [ ]:
BDOSS['POS'].unique()

Meanings of POS's unique values:
- ENC: Normal state;
- SAN: Client settles before date;
- SOL: Client settles on contract termination date;
- RBT: Same as SAN (business wise).

Since RBT is the same as SAN, we will update our dataset so that every RBT turns into SAN.

In [ ]:
BDOSS['RN'].value_counts()

RN is a red flag feature, the higher it's value, the higher the chance a client will churn.

In [ ]:
BDOSS['POLE'].value_counts()

Not specified in MetaData, however, we were told that:
- P: Direct business;
- N: Sales for business partners.

**- PRODALP**

In [ ]:
BDOSS['PRODALP'].value_counts()

None of these unique values appear in our MetaData. However, we were told that:
- EP - most used when the clients want to churn; 
- EXT, EPF, DEF: Personal loans.

**- CSP**

In [ ]:
BDOSS['CSP'].unique()

The values 54, 58, 50, 56, 55, 57, 52, 53, 0 and 51 also don't appear in our MetaData.

In [ ]:
missing = [54, 58, 50, 56, 55, 57, 52, 53, 0, 51]
result = 0
for num in BDOSS['CSP']:
    if num in missing:
        result = result + 1
print(result)

In [ ]:
result / len(BDOSS['CSP']) * 100

These values correspond to around 6% of our data

**- RISK AND RISKA**

In [ ]:
BDOSS[BDOSS['RISKA'] != BDOSS['RISK'].astype(str).str[-1].astype(int)]

In [ ]:
168528 / len(BDOSS) * 100

Here, we can see that only around 6% of our data has a RISKA value diferent than the last number of RISK.

**- RANGPRO AND DURDEG**

In [ ]:
BDOSS[BDOSS['RANGPRO'] - BDOSS['DURDEG'] > 0]

In [ ]:
BDOSS[BDOSS['RANGPRO'] - BDOSS['DURDEG'] == 0]

In the cells above, we can see that there are 253 rows in BDOSS with a RANGPRO value higher than it's respective DURDEG value. We can also see that this diference is exactly 1 in every row.

<a class="anchor" id="2.2 Analysing the Data">

## 3. Data Preparation
    
</a>

### 3.1. Changing Datatypes

In [36]:
BDOSS['BICONTRATO'] = BDOSS['BICONTRATO'].round().astype('Int32')
BDOSS['DURDEG'] = BDOSS['DURDEG'].round().astype('Int32')
BDOSS['RANGPRO'] = BDOSS['RANGPRO'].round().astype('Int32')
BDOSS['RANGCLI'] = BDOSS['RANGCLI'].round().astype('Int32')
BDOSS['RISKA'] = BDOSS['RISKA'].round().astype('Int32')
BDOSS['CSP'] = BDOSS['CSP'].round().astype('Int32')
BDOSS['DCSP'] = BDOSS['DCSP'].round().astype('Int32')

In [37]:
BDOSS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2658187 entries, 0 to 2658186
Data columns (total 35 columns):
 #   Column             Dtype
---  ------             -----
 0   CONTRIB            object
 1   DOSSIER            object
 2   POLE               object
 3   TYPEPROD           object
 4   PRODALP            object
 5   BICONTRATO         Int32
 6   POS                object
 7   OBS_DATE           datetime64[ns]
 8   DCREAT             datetime64[ns]
 9   DATFIN             datetime64[ns]
 10  D1FIN              datetime64[ns]
 11  DPOS               datetime64[ns]
 12  DURDEG             Int32
 13  RANGPRO            Int32
 14  RANGCLI            Int32
 15  MTFINO             float64
 16  MTFIN              float64
 17  MENSALIDADE        float64
 18  MENSALIDADE_CORR   float64
 19  CRD                float64
 20  SREC               float64
 21  ACTIVIDADE_GLOBAL  float64
 22  RN                 float64
 23  RD                 float64
 24  RISK               object
 25  RISKA              Int32
 26  AGFIN              float64
 27  PAGAMENTO          object
 28  RESSO              float64
 29  CSP                Int32
 30  DCSP               Int32
 31  NATIO              object
 32  PTT                object
 33  NBENF              float64
 34  MODCONTACTO        object
dtypes: Int32(7), datetime64[ns](5), float64(12), object(11)
memory usage: 656.6+ MB

### 3.2. Handling Incoherencies

In [38]:
#replacing every RBT with SAN
BDOSS['POS'] = BDOSS['POS'].replace('RBT', 'SAN')

In [39]:
#Correcting observations so every RISKA value corresponds to the last number of it's respective RISK value.
mask = BDOSS['RISKA'] != BDOSS['RISK'].astype(str).str[-1].astype(int)

BDOSS.loc[mask, 'RISK'] = (BDOSS.loc[mask, 'RISK'].astype(str).str[:-1] + 
                           BDOSS.loc[mask, 'RISKA'].astype(str))

BDOSS[BDOSS['RISKA'] != BDOSS['RISK'].astype(str).str[-1].astype(int)]

Empty DataFrame
Columns: [CONTRIB, DOSSIER, POLE, TYPEPROD, PRODALP, BICONTRATO, POS, OBS_DATE, DCREAT, DATFIN, D1FIN, DPOS, DURDEG, RANGPRO, RANGCLI, MTFINO, MTFIN, MENSALIDADE, MENSALIDADE_CORR, CRD, SREC, ACTIVIDADE_GLOBAL, RN, RD, RISK, RISKA, AGFIN, PAGAMENTO, RESSO, CSP, DCSP, NATIO, PTT, NBENF, MODCONTACTO]
Index: []

In [40]:
mask = (BDOSS['RANGPRO'] == BDOSS['DURDEG'] + 1)
BDOSS.loc[mask, 'RANGPRO'] = BDOSS.loc[mask, 'DURDEG']
#BDOSS.loc[mask, 'DURDEG'] = BDOSS.loc[mask, 'RANGPRO']

### 3.3. Handling Missing Values

In [41]:
#checking number of missing values in each column as a percentage
BDOSS.isna().sum()[BDOSS.isna().sum() > 0]/len(BDOSS) * 100

RANGCLI                0.000038
MENSALIDADE_CORR     100.000000
ACTIVIDADE_GLOBAL    100.000000
DCSP                  11.047492
NATIO                  0.000038
NBENF                  0.027688
MODCONTACTO            2.240023
dtype: float64

In [42]:
BDOSS.isna().sum()[BDOSS.isna().sum() > 0]

RANGCLI                    1
MENSALIDADE_CORR     2658187
ACTIVIDADE_GLOBAL    2658187
DCSP                  293663
NATIO                      1
NBENF                    736
MODCONTACTO            59544
dtype: int64

In [43]:
#droping 'MENSALIDADE_CORR' and'ACTIVIDADE_GLOBAL' due to its elevated number of missing values
BDOSS = BDOSS.drop(columns=['MENSALIDADE_CORR'])
BDOSS = BDOSS.drop(columns=['ACTIVIDADE_GLOBAL'])

In [44]:
#filling missing values of categorical variables with mode
for col in ['RANGCLI', 'NATIO', 'MODCONTACTO']:
    BDOSS[col] = BDOSS[col].fillna(BDOSS[col].mode()[0])

#filling missing values of numeric variables with median
for col in ['DCSP', 'NBENF']:
    BDOSS[col] = BDOSS[col].fillna(BDOSS[col].median())

#mudar para knn imputer

### 3.4. Handling Outliers

In [45]:
BDOSS['MTFINO'] = BDOSS['MTFINO'].clip(upper=80000)
BDOSS['MTFIN'] = BDOSS['MTFIN'].clip(upper=80000)
BDOSS['MENSALIDADE'] = BDOSS['MENSALIDADE'].clip(upper=4000)
BDOSS['CRD'] = BDOSS['CRD'].clip(upper=100000)
BDOSS['SREC'] = BDOSS['SREC'].clip(upper=40000)
BDOSS['RESSO'] = BDOSS['RESSO'].clip(upper=700000)
BDOSS['NBENF'] = BDOSS['NBENF'].clip(upper=10)

### 3.5. Feature Engineering

In [46]:
# garantir ordem temporal
BDOSS = BDOSS.sort_values(['CONTRIB', 'DOSSIER', 'OBS_DATE']).copy()

# contar quantas vezes já apareceu CRD == 0 dentro de cada contrato
zero_count = (
    BDOSS['CRD'].eq(0)
    .groupby([BDOSS['CONTRIB'], BDOSS['DOSSIER']])
    .cumsum()
)

# manter:
# - todas as linhas com CRD != 0
# - apenas a primeira linha com CRD == 0
BDOSS = BDOSS[(BDOSS['CRD'] != 0) | (zero_count == 1)].copy()

In [47]:
BDOSS['DIF_CRD_NEXT'] = BDOSS['CRD'] - (BDOSS.groupby(['CONTRIB', 'DOSSIER'])['CRD'].shift(-1))
col = BDOSS.pop('DIF_CRD_NEXT')
BDOSS.insert(19, 'DIF_CRD_NEXT', col)
BDOSS.head()

,CONTRIB,DOSSIER,POLE,TYPEPROD,PRODALP,BICONTRATO,POS,OBS_DATE,DCREAT,DATFIN,D1FIN,DPOS,DURDEG,RANGPRO,RANGCLI,MTFINO,MTFIN,MENSALIDADE,CRD,DIF_CRD_NEXT,SREC,RN,RD,RISK,RISKA,AGFIN,PAGAMENTO,RESSO,CSP,DCSP,NATIO,PTT,NBENF,MODCONTACTO
576857,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,36cc29a11081476fb7fcaed11aafef6fd441c3d172f4ff...,P,CL,EP,0,ENC,2024-06-30,2024-06-25,2024-06-27,2024-06-27,2024-06-27,84,0,19,8000.0,8000.0,158.359889,9575.287,77.933,0.0,0.0,0.0,000000000000000000000000,0,118.0,P,1278.521,74,2020,P,8600,0.0,W
694260,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,36cc29a11081476fb7fcaed11aafef6fd441c3d172f4ff...,P,CL,EP,0,ENC,2024-07-31,2024-06-25,2024-06-27,2024-06-27,2024-06-27,84,1,19,8000.0,8000.0,158.359889,9497.354,78.628,0.0,0.0,0.0,000000000000000000000000,0,118.0,P,1278.521,74,2020,P,8600,0.0,W
812122,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,36cc29a11081476fb7fcaed11aafef6fd441c3d172f4ff...,P,CL,EP,0,ENC,2024-08-31,2024-06-25,2024-06-27,2024-06-27,2024-06-27,84,2,19,8000.0,8000.0,158.359889,9418.726,9418.726,0.0,0.0,0.0,000000000000000000000000,0,118.0,P,1513.466,80,2024,P,8600,0.0,W
930223,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,36cc29a11081476fb7fcaed11aafef6fd441c3d172f4ff...,P,CL,EP,0,SAN,2024-09-30,2024-06-25,2024-06-27,2024-06-27,2024-10-03,84,3,19,8000.0,8000.0,158.359889,0.000,NaN,0.0,0.0,0.0,000000000000000000000000,0,118.0,P,1513.466,80,2024,P,8600,0.0,W
930224,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,a34f4d89a43b924b483dc829a65ccba8b0f90e0afc2063...,P,CL,EP,0,ENC,2024-09-30,2024-09-13,2024-09-30,2024-09-30,2024-09-30,120,1,19,16000.0,16000.0,280.401466,19336.270,82.508,0.0,0.0,0.0,000000000000000000000000,0,118.0,P,1513.466,80,2024,P,8600,0.0,W

**- DELAY (amount of time, in months, that the client delayed payments)**

In [48]:
BDOSS['DELAY'] = BDOSS['RANGCLI'] - BDOSS['RANGPRO']

In [49]:
#BDOSS['DELAY'] = BDOSS['RANGCLI'] - BDOSS['RANGPRO']
conditions = [
    BDOSS['DIF_CRD_NEXT'] == 0.00,                   # não pagou
    BDOSS['DIF_CRD_NEXT'] > BDOSS['MENSALIDADE'],   # pagou mais
    BDOSS['DIF_CRD_NEXT'] < BDOSS['MENSALIDADE']   # pagou normal
]

choices = [-1, 1, 0]

BDOSS['DELAY'] = np.select(conditions, choices, default=0)

In [50]:
BDOSS

,CONTRIB,DOSSIER,POLE,TYPEPROD,PRODALP,BICONTRATO,POS,OBS_DATE,DCREAT,DATFIN,D1FIN,DPOS,DURDEG,RANGPRO,RANGCLI,MTFINO,MTFIN,MENSALIDADE,CRD,DIF_CRD_NEXT,SREC,RN,RD,RISK,RISKA,AGFIN,PAGAMENTO,RESSO,CSP,DCSP,NATIO,PTT,NBENF,MODCONTACTO,DELAY
576857,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,36cc29a11081476fb7fcaed11aafef6fd441c3d172f4ff...,P,CL,EP,0,ENC,2024-06-30,2024-06-25,2024-06-27,2024-06-27,2024-06-27,84,0,19,8000.0,8000.0,158.359889,9575.287,77.933,0.000,0.0,0.0,000000000000000000000000,0,118.0,P,1278.521,74,2020,P,8600,0.0,W,0
694260,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,36cc29a11081476fb7fcaed11aafef6fd441c3d172f4ff...,P,CL,EP,0,ENC,2024-07-31,2024-06-25,2024-06-27,2024-06-27,2024-06-27,84,1,19,8000.0,8000.0,158.359889,9497.354,78.628,0.000,0.0,0.0,000000000000000000000000,0,118.0,P,1278.521,74,2020,P,8600,0.0,W,0
812122,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,36cc29a11081476fb7fcaed11aafef6fd441c3d172f4ff...,P,CL,EP,0,ENC,2024-08-31,2024-06-25,2024-06-27,2024-06-27,2024-06-27,84,2,19,8000.0,8000.0,158.359889,9418.726,9418.726,0.000,0.0,0.0,000000000000000000000000,0,118.0,P,1513.466,80,2024,P,8600,0.0,W,1
930223,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,36cc29a11081476fb7fcaed11aafef6fd441c3d172f4ff...,P,CL,EP,0,SAN,2024-09-30,2024-06-25,2024-06-27,2024-06-27,2024-10-03,84,3,19,8000.0,8000.0,158.359889,0.000,NaN,0.000,0.0,0.0,000000000000000000000000,0,118.0,P,1513.466,80,2024,P,8600,0.0,W,0
930224,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,a34f4d89a43b924b483dc829a65ccba8b0f90e0afc2063...,P,CL,EP,0,ENC,2024-09-30,2024-09-13,2024-09-30,2024-09-30,2024-09-30,120,1,19,16000.0,16000.0,280.401466,19336.270,82.508,0.000,0.0,0.0,000000000000000000000000,0,118.0,P,1513.466,80,2024,P,8600,0.0,W,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112222,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,5f58cce05624b68e1c810c7eddea58a455e4e519b1d56a...,P,CL,EPF,0,ENC,2024-01-31,2022-03-24,2022-03-31,2022-03-31,2023-09-15,84,22,34,12000.0,12000.0,267.471639,11686.385,141.249,0.000,0.0,0.0,000000000000000000100001,1,117.0,P,916.467,80,2014,P,2845,0.0,A,0
226249,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,5f58cce05624b68e1c810c7eddea58a455e4e519b1d56a...,P,CL,EPF,0,ENC,2024-02-29,2022-03-24,2022-03-31,2022-03-31,2024-02-29,84,23,34,12000.0,12000.0,267.471639,11545.136,11545.136,0.000,0.0,0.0,000000000000000001000000,0,117.0,P,916.467,80,2014,P,2845,0.0,A,1
342740,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,5f58cce05624b68e1c810c7eddea58a455e4e519b1d56a...,P,CL,EPF,0,SAN,2024-03-31,2022-03-24,2022-03-31,2022-03-31,2024-03-27,84,23,34,12000.0,12000.0,267.471639,0.000,NaN,700.531,0.0,0.0,000000000000000010000010,0,117.0,P,1034.366,80,2014,P,2845,0.0,A,0
112223,ffff943c736f98d4840f65328ba372a29689312dd781b4...,028095f193e6a9ceaf6878e2f08ea30b2218d02b27d23d...,P,CL,EP,0,ENC,2024-01-31,2023-10-23,2023-10-30,2023-10-30,2023-10-30,24,3,6,2500.0,2500.0,135.336545,2572.760,NaN,0.000,1.0,12.0,000000000000000000000101,1,119.0,P,924.580,60,2005,P,2825,0.0,A,0
112224,ffffe82f7c91df4a087341fe89db094be2a89294f21785...,159941797f0c7dd45dcb8638c273da1614078db068e330...,P,CL,EPF,0,SAN,2024-01-31,2021-02-10,2021-02-15,2021-02-15,2023-10-12,84,32,87,20000.0,20000.0,415.242666,0.000,NaN,0.000,0.0,0.0,000000000000000000000000,0,117.0,P,2234.521,60,2002,P,2730,1.0,A,0

In [51]:
#survival methods
# ordenar
BDOSS = BDOSS.sort_values(['CONTRIB', 'DOSSIER', 'OBS_DATE']).copy()

# última OBS_DATE de cada dossier, replicada em todas as linhas do grupo
BDOSS['LAST_OBS_DATE'] = BDOSS.groupby(['CONTRIB', 'DOSSIER'])['OBS_DATE'].transform('max')

# tempo em meses inteiros
BDOSS['TIME_MONTHS'] = (
    (BDOSS['LAST_OBS_DATE'].dt.year - BDOSS['DCREAT'].dt.year) * 12
    + (BDOSS['LAST_OBS_DATE'].dt.month - BDOSS['DCREAT'].dt.month)
)

### 3.5. Data Aggregation

**Data Agregation**

We will start by agregating every DOSSIER per client.

In [52]:
agg_dossier = (BDOSS.groupby(['CONTRIB', 'DOSSIER']).agg(
    #counting every 'POS' result
    #sol_count = ('POS', lambda x: (x == 'SOL').sum()),
    #san_count = ('POS', lambda x: (x == 'SAN').sum()),
    #enc_count = ('POS', lambda x: (x == 'ENC').sum()),
    #rbt_count = ('POS', lambda x: (x == 'RBT').sum()),
    is_san=('POS', lambda x: int(x.eq('SAN').any())),
    is_sol=('POS', lambda x: int(x.eq('SOL').any())),
    
    #DURDEG, MTFINO and MENSALIDADE are constant in the dossier
    #RANGPRO, RANGCLI e HISTORIAL - max
    #CRD - min 
    #RESSO AND NBENF - mean
    #AGFIN, PAGAMENTO, CSP, NATIO, PTT and MODCONTACTO - mode
    #faltam: POLE, PRODALP, RN, DATAS IMPORTANTES, SHREK
    
    DCREAT = ('DCREAT', 'first'),
    DCRD_0 = ('OBS_DATE', lambda x: x[BDOSS.loc[x.index, 'CRD'] == 0].min()),
    CLOSE_DATE = ('OBS_DATE', lambda x: x[BDOSS.loc[x.index, 'POS'].isin(['SAN','SOL'])].min()),

    DURDEG = ('DURDEG', 'first'),
    RANGPRO_max = ('RANGPRO', 'max'),
    RANGCLI_max = ('RANGCLI', 'max'),
    delay_mean = ('DELAY', 'mean'),
    delay_max = ('DELAY', 'max'),
    
    MENSALIDADE = ('MENSALIDADE', 'first'),     
    CRD_min = ('CRD', 'min'),
    MTFINO = ('MTFINO', 'first'),
    RESSO_mean = ('RESSO', 'mean'),
    RISKA_mean = ('RISKA', 'mean'),
    NBENF_mean = ('NBENF', 'mean'),
    RN_mean = ('RN', 'mean'),
    SREC = ('SREC', 'mean'),

    POLE = ('POLE', moda),
    PRODALP = ('PRODALP', moda),
    AGFIN = ('AGFIN', moda),
    PAGAMENTO = ('PAGAMENTO', moda),
    CSP = ('CSP', moda),
    NATIO = ('NATIO', moda),
    PTT = ('PTT', moda),
    MODCONTACTO = ('MODCONTACTO', moda),
).reset_index())

In [53]:
agg_dossier

,CONTRIB,DOSSIER,is_san,is_sol,DCREAT,DCRD_0,CLOSE_DATE,DURDEG,RANGPRO_max,RANGCLI_max,delay_mean,delay_max,MENSALIDADE,CRD_min,MTFINO,RESSO_mean,RISKA_mean,NBENF_mean,RN_mean,SREC,POLE,PRODALP,AGFIN,PAGAMENTO,CSP,NATIO,PTT,MODCONTACTO
0,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,36cc29a11081476fb7fcaed11aafef6fd441c3d172f4ff...,1,0,2024-06-25,2024-09-30,2024-09-30,84,3,19,0.250000,1,158.359889,0.000,8000.00,1395.993500,0.0,0.0,0.0,0.000000,P,EP,118.0,P,74,P,8600,W
1,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,a34f4d89a43b924b483dc829a65ccba8b0f90e0afc2063...,1,0,2024-09-13,2025-11-30,2025-11-30,120,13,19,0.111111,1,280.401466,0.000,16000.00,1513.466000,0.0,0.0,0.0,0.000000,P,EP,118.0,P,80,P,8600,W
2,0000ab2116257783438c70ff85a3e98f2d4194ebe53434...,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956...,0,0,2018-03-29,NaT,NaT,120,91,91,0.000000,1,347.447280,8115.247,20000.00,1113.258000,0.0,1.0,0.0,15.106391,P,EP,120.0,P,80,P,2845,A
3,0000c74654405ec1da4dbdcd00b86e397954043965d98e...,1c848abbdf2867f690d6c07cd30f110a0b49fcd44b7202...,0,1,2001-09-27,2024-03-31,2024-03-31,60,21,21,0.000000,0,184.214593,0.000,5985.57,678.483000,0.0,2.0,1.0,0.000000,P,EP,117.0,P,60,P,2745,T
4,0000c74654405ec1da4dbdcd00b86e397954043965d98e...,796b87efb05b1ec3f822189b7b5fe25be06390e7462d22...,0,1,2001-09-21,2024-03-31,2024-03-31,60,21,21,0.000000,0,424.699203,0.000,13467.54,678.483000,0.0,2.0,1.0,0.000000,P,EP,117.0,P,60,P,2745,T
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185595,fffc991d73df732084dab58938d520b8a5d8712474fa53...,8a1945dd1c8ef5d381bef27f69ef52bd6b19729822aea7...,0,1,2021-02-12,2024-01-31,2024-01-31,34,34,34,0.000000,0,57.095138,0.000,1500.00,896.196000,0.0,1.0,0.0,0.000000,P,EP,118.0,P,80,P,4400,W
185596,fffd54b6dbb4cc001fb8ab52a905cff9bdbf14b747be9a...,b6e4983596a5a38f9bfd54da8bff33bcae0bfc46138f9a...,0,0,2021-06-17,NaT,NaT,60,53,53,0.000000,1,416.654611,2563.528,15000.00,1623.880000,0.0,0.0,0.0,0.000000,P,EP,120.0,P,80,P,9560,W
185597,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,5f58cce05624b68e1c810c7eddea58a455e4e519b1d56a...,1,0,2022-03-24,2024-03-31,2024-03-31,84,23,34,0.333333,1,267.471639,0.000,12000.00,955.766667,0.333333,0.0,0.0,233.510333,P,EPF,117.0,P,80,P,2845,A
185598,ffff943c736f98d4840f65328ba372a29689312dd781b4...,028095f193e6a9ceaf6878e2f08ea30b2218d02b27d23d...,0,0,2023-10-23,NaT,NaT,24,3,6,0.000000,0,135.336545,2572.760,2500.00,924.580000,1.0,0.0,1.0,0.000000,P,EP,119.0,P,60,P,2825,A
185599,ffffe82f7c91df4a087341fe89db094be2a89294f21785...,159941797f0c7dd45dcb8638c273da1614078db068e330...,1,0,2021-02-10,2024-01-31,2024-01-31,84,32,87,0.000000,0,415.242666,0.000,20000.00,2234.521000,0.0,1.0,0.0,0.000000,P,EPF,117.0,P,60,P,2730,A

In [ ]:
dup_check = BDOSS.groupby('DOSSIER')['CONTRIB'].nunique()
dup_check[dup_check > 1]

After this first agregation we can see that 8 dossiers appear twice on our agg_dossier DataFrame.

We determined that the reason is for the clients to be married and share the dossiers.

In [ ]:
def next_valid_dossier(group):
    group = group.copy()

    next_dates = []
    dcreat = group['DCREAT'].values
    close = group['CLOSE_DATE'].values

    for i in range(len(group)):
        if pd.isna(close[i]):   
            next_dates.append(pd.NaT)
            continue

        future_loans = dcreat[dcreat > close[i]]

        if len(future_loans) > 0:
            next_dates.append(future_loans.min())
        else:
            next_dates.append(pd.NaT)

    group['NEXT_DOSSIER_DATE'] = next_dates

    return group

In [ ]:
agg_dossier = (agg_dossier.groupby('CONTRIB', group_keys=False).apply(next_valid_dossier))

In [ ]:
agg_dossier['DAYS_TO_NEXT'] = (agg_dossier['NEXT_DOSSIER_DATE'] - agg_dossier['CLOSE_DATE']).dt.days

agg_dossier['CHURN'] = None

closed = agg_dossier['CLOSE_DATE'].notna()

agg_dossier.loc[closed, 'CHURN'] = (
    (agg_dossier.loc[closed, 'DAYS_TO_NEXT'] > 30) |
    (agg_dossier.loc[closed, 'DAYS_TO_NEXT'].isna()))

In [ ]:
agg_dossier#[agg_dossier['CONTRIB'] == '00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981']#.iloc[0, 1]#['DAYS_TO_NEXT'].sort_values(ascending = False)

In [ ]:
agg_dossier['CHURN'].unique()

In [ ]:
agg_dossier[agg_dossier['CHURN'] == True]

In [ ]:
agg_dossier[agg_dossier['CHURN'] == False]

In [ ]:
agg_dossier[agg_dossier['CHURN'].isna()]

In [ ]:
print(agg_dossier[agg_dossier['CHURN'].isna()]['sol_count'].sum(), agg_dossier[agg_dossier['CHURN'].isna()]['san_count'].sum())

In [ ]:
agg_dossier[(agg_dossier['sol_count'] > 0) & (agg_dossier['san_count'] > 0)]

In [ ]:
#agg_dossier.drop('CHURN', axis = 1, inplace = True)
agg_dossier.drop('NEXT_DOSSIER_DATE', axis = 1, inplace = True)
agg_dossier.drop('next_dossier_date', axis = 1, inplace = True)
agg_dossier.drop('DAYS_TO_NEXT', axis = 1, inplace = True)

---

In [ ]:
agg_dossier = agg_dossier.sort_values(['CONTRIB','DCREAT'])

agg_dossier['NEXT_DATE'] = (agg_dossier.groupby('CONTRIB')['DCREAT'].shift(-1))

agg_dossier['DAYS_TO_NEXT'] = (agg_dossier['NEXT_DATE'] - agg_dossier['CLOSE_DATE']).dt.days

agg_dossier['CHURN'] = agg_dossier['DAYS_TO_NEXT'] > 30
#agg_dossier['CHURN'] = agg_dossier['CHURN'].fillna(True)

In [ ]:
agg_dossier['CHURN'].isna().sum()

In [ ]:
agg_dossier['CHURN'].value_counts()

In [ ]:
agg_dossier#['CLOSE_DATE'].isna().sum()

In [ ]:
agg_dossier.drop('CHURN', axis = 1, inplace = True)
agg_dossier.drop('NEXT_DATE', axis = 1, inplace = True)
agg_dossier.drop('DAYS_TO_NEXT', axis = 1, inplace = True)

In [ ]:
falar

In [ ]:
BDOSS = BDOSS.sort_values(['CONTRIB','DOSSIER','OBS_DATE'])

In [ ]:
agg_dossier[(agg_dossier['sol_count'] > 1) | (agg_dossier['san_count'] > 1)]#['DOSSIER'].iloc[1]

In [ ]:
agg_dossier[agg_dossier['san_count'] > 1]

In [ ]:
74813 - 74940

In [ ]:
#BDOSS[BDOSS['DOSSIER'] == '36cc29a11081476fb7fcaed11aafef6fd441c3d172f4ffb8db787131bb069c76']

In [ ]:
#BDOSS[BDOSS['DOSSIER'] == '1c848abbdf2867f690d6c07cd30f110a0b49fcd44b7202d95cfd8ba504a84f6c']

We can see 74106 cases where the clients terminated their contracts more than once.

In [ ]:
agg_dossier[(agg_dossier['sol_count'] >= 1) & (agg_dossier['san_count'] >= 1)]#['DOSSIER'].iloc[0]

In [ ]:
BDOSS[BDOSS['DOSSIER'] == '9fbf61ef9c2c34b684b7cda914a5ec2b26b76807f0c9914052ae9ede81f2222f']

We can see 3 cases where where the clients did both san and sol in the same dossier.

In [ ]:
agg_dossier[(agg_dossier['sol_count'] > 1) & (agg_dossier['DURDEG'] - agg_dossier['RANGPRO_max'] != 0)]

----

Now, we will proceed to the agregation of our clients.

In [ ]:
agg_clients = (agg_dossier.groupby('CONTRIB').agg(
    n_dossiers=('DOSSIER', 'nunique'),

    #contagens do POS
    sol_count=('sol_count', 'sum'),
    san_count=('san_count', 'sum'),
    enc_count=('enc_count', 'sum'),
    rbt_count=('rbt_count', 'sum'),
    #enc_after_san_sol=('enc_after_san_sol_count', 'sum'), ainda nao foi decidido se se faz

    #DURDEG, MTFINO e MENSALIDADE
    #RANGPRO, RANGCLI e HISTORIAL
    #CRD, RESSO e NBENF
    #AGFIN, PAGAMENTO, CSP, NATIO, PTT e MODCONTACTO
    
    DURDEG = ('DURDEG', 'mean'),
    RANGPRO = ('RANGPRO_max', 'mean'),
    RANGCLI = ('RANGCLI_max', 'mean'),
    MENSALIDADE = ('MENSALIDADE', 'mean'), 
    CRD = ('CRD_min', 'mean'),

    MTFINO = ('MTFINO', 'mean'),
    RESSO = ('RESSO_mean', 'mean'),
    RISKA = ('RISKA_mean', 'mean'),
    NBENF = ('NBENF_mean', 'mean'),

    AGFIN = ('AGFIN', moda),
    PAGAMENTO = ('PAGAMENTO', moda),
    CSP = ('CSP', moda),
    NATIO = ('NATIO', moda),
    PTT = ('PTT', moda),
    MODCONTACTO = ('MODCONTACTO', moda),
))

In [ ]:
agg_clients

<a class="anchor" id="2.2 Analysing the Data">

## 4. Merging Datasets
    
</a>

In [ ]:
BNP = (
    agg_dossier
    .merge(CRC_agg, on='CONTRIB', how='left')
    .merge(CREDSCORE, on='CONTRIB', how='left')
    .merge(FAMA, on='CONTRIB', how='left')
    .set_index('CONTRIB')
)
BNP.head()

## **DATA VISUALIZATION**

Before we start our Data Visualization, we will separate our numerical and categorical features in agg_clients DataFrame:

In [ ]:
cat_cols = ['AGFIN', 'PAGAMENTO', 'CSP', 'NATIO', 'PTT', 'MODCONTACTO']
agg_clients_cat = agg_clients[cat_cols]

num_cols = ['n_dossiers', 'sol_count', 'san_count', 'enc_count', 'rbt_count', 'DURDEG', 'RANGPRO', 'RANGCLI', 'RISKA', 'MTFINO', 'MENSALIDADE', 'CRD', 'RESSO', 'NBENF']
agg_clients_num = agg_clients[num_cols]

**- Numerical Features**

Before we begin the visualization of our numerical features, we will clean the data further by dealing with missing values.

In [ ]:
agg_clients_num.isna().sum()

In the output of the cell above, we can see that NBENF has 40 missing values.

In [ ]:
knn = KNNImputer(n_neighbors = 5, weights = 'distance')
agg_clients_num['NBENF'] = knn.fit_transform(agg_clients_num)

We used KNN (with 5 neighbors) to fill those missing values.

**Histograms:**

In [ ]:
n = len(num_cols)
fig, axes = plt.subplots(nrows = (n // 3) + 1, ncols = 3, figsize = (15, 20))
axes = axes.flatten()

for i, col in enumerate(num_cols):
    axes[i].hist(agg_clients_num[col].dropna(), bins = 20, color = '#5dade2', edgecolor = 'black')
    axes[i].set_title(col)
    axes[i].set_xlabel('')
    #axes[i].set_ylabel('Frequency')

for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

**Boxplots:**

In [ ]:
def plot_multiple_boxplots(data, feats):
    
    n = len(feats)  # número de features
    ncols = 3
    nrows = (n // ncols) + (n % ncols > 0)
    
    fig, axes = plt.subplots(nrows=nrows, ncols=ncols, figsize=(15, 5*nrows))
    axes = axes.flatten()
    
    for i, feat in enumerate(feats):
        # garantir que é numérica
        data[feat] = pd.to_numeric(data[feat], errors="coerce")
        
        # remover NaNs para evitar erro
        clean_data = data[feat].dropna()
        
        if len(clean_data) > 0:
            sns.boxplot(x=clean_data, ax=axes[i], color="#5dade2")
            axes[i].set_title(feat)
        else:
            axes[i].set_visible(False)
    
    # remover eixos extra
    for j in range(i+1, len(axes)):
        fig.delaxes(axes[j])
    
#    plt.suptitle(title, fontsize=20)
    plt.tight_layout()
    plt.show()

plot_multiple_boxplots(agg_clients_num, num_cols)

**Correlation:**

In [ ]:
cor_spearman = agg_clients_num.corr(method ='spearman')
#mask = (cor_spearman.abs() < 0.5)
mask = np.triu(np.ones_like(cor_spearman, dtype=bool))

plt.figure(figsize=(12,8))
sns.heatmap(cor_spearman, 
            annot=True, 
            mask=mask,
            cmap = "Blues", 
            center=0)

plt.title("Correlation")
plt.show()

In [ ]:
agg_clients_num[agg_clients_num['RANGPRO'] == agg_clients_num['RANGCLI']]

In the output above we can see that 82009 clients have always kept to date with their payments.

In [ ]:
agg_clients_num[agg_clients_num['rbt_count'] == 40]

Here, we can see a client who has churned 40 times.

In [ ]:
agg_clients_num[agg_clients_num['rbt_count'] > agg_clients_num['n_dossiers']]

In [ ]:
len(agg_clients_num[agg_clients_num['rbt_count'] > agg_clients_num['n_dossiers']]) / len(agg_clients_num) * 100

In [ ]:
agg_clients_num['RISKA'].value_counts()

**- Categorical Features**

In [ ]:
agg_clients_cat

Before we begin the visualization of our categorical features, we will see their distribution and deal with missing values.

In [ ]:
for col in agg_clients_cat.columns:
    print(agg_clients_cat[col].value_counts())

In [ ]:
agg_clients_cat.isna().sum()

In the output of the cell above, we can see 5161 missing values in MODCONTACT.

In [ ]:
agg_clients_cat['MODCONTACTO'].fillna(agg_clients_cat['MODCONTACTO'].mode()[0], inplace=True)

We decided to fill these missing values using the feature's mode.

In [ ]:
top_postal = agg_clients_cat['PTT'].value_counts().nlargest(10)

sns.barplot(x = top_postal.values, y = top_postal.index)
plt.title('Top 10 Postal Codes')
plt.show()

In [ ]:
fig, axes = plt.subplots(nrows = 2, ncols = 2, figsize = (10, 10))
axes = axes.flatten()
cols = ['PAGAMENTO', 'MODCONTACTO', 'NATIO', 'AGFIN']
for i, col in enumerate(cols):
    axes[i].hist(agg_clients_cat[col].dropna(), bins = 20, color = '#5dade2', edgecolor = 'black')
    axes[i].set_title(col)
    axes[i].set_xlabel('')
    #axes[i].set_ylabel('Frequency')

for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

In [ ]:
top_csp = agg_clients_cat['CSP'].value_counts().nlargest(5)

sns.barplot(x = top_csp.values, y = top_csp.index)
plt.title('Top 5 most used CSP')
plt.show()